const airports = {
    "addressAirportAll":[
            {
                "airportCName":"梧州长洲岛机场",
                "airportCode":"WUZ",
                "cityCName":"梧州",
                "cityEName":"Wuzhou",
                "cityFirstSpell":"wz",
                "citySpell":"wuzhou"
            },
            {
                "airportCName":"黄果树机场",
                "airportCode":"AVA",
                "cityCName":"安顺",
                "cityEName":"Anshun",
                "cityFirstSpell":"as",
                "citySpell":"anshun"
            },
            {
                "airportCName":"贵阳机场",
                "airportCode":"KWE",
                "cityCName":"贵阳",
                "cityEName":"Guiyang",
                "cityFirstSpell":"gy",
                "citySpell":"guiyang"
            },
            {
                "airportCName":"铜仁机场",
                "airportCode":"TEN",
                "cityCName":"铜仁",
                "cityEName":"Tongren",
                "cityFirstSpell":"tr",
                "citySpell":"tongren"
            },
            {
                "airportCName":"遵义新舟机场",
                "airportCode":"ZYI",
                "cityCName":"遵义新舟",
                "cityEName":"ZunyiXinzhou",
                "cityFirstSpell":"zyxz",
                "citySpell":"zunyixinzhou"
            },
            {
                "airportCName":"海口美兰机场",
                "airportCode":"HAK",
                "cityCName":"海口",
                "cityEName":"Haikou",
                "cityFirstSpell":"hk",
                "citySpell":"haikou"
            },
            {
                "airportCName":"邯郸机场",
                "airportCode":"HDG",
                "cityCName":"邯郸",
                "cityEName":"Handan",
                "cityFirstSpell":"hd",
                "citySpell":"handan"
            },
            {
                "airportCName":"黄骅治蝗机场",
                "airportCode":"HHA",
                "cityCName":"黄骅",
                "cityEName":"Huangye",
                "cityFirstSpell":"hh",
                "citySpell":"huanghua"
            },
            {
                "airportCName":"石家庄正定机场",
                "airportCode":"SJW",
                "cityCName":"石家庄",
                "cityEName":"Shijiazhuang",
                "cityFirstSpell":"sjz",
                "citySpell":"shijiazhuang"
            },
            {
                "airportCName":"洛阳机场",
                "airportCode":"LYA",
                "cityCName":"洛阳",
                "cityEName":"LuoYang",
                "cityFirstSpell":"ly",
                "citySpell":"luoyang"
            },
            {
                "airportCName":"哈尔滨太平国际机场",
                "airportCode":"HRB",
                "cityCName":"哈尔滨",
                "cityEName":"Harbin",
                "cityFirstSpell":"heb",
                "citySpell":"haerbin"
            },
            {
                "airportCName":"佳木斯机场",
                "airportCode":"JMU",
                "cityCName":"佳木斯",
                "cityEName":"Jiamusi",
                "cityFirstSpell":"jms",
                "citySpell":"jiamusi"
            },
            {
                "airportCName":"牡丹江海浪机场",
                "airportCode":"MDG",
                "cityCName":"牡丹江",
                "cityEName":"Mudanjiang",
                "cityFirstSpell":"mdj",
                "citySpell":"mudanjiang"
            },
            {
                "airportCName":"恩施机场",
                "airportCode":"ENH",
                "cityCName":"恩施",
                "cityEName":"Enshi",
                "cityFirstSpell":"es",
                "citySpell":"enshi"
            },
            {
                "airportCName":"那拉提机场",
                "airportCode":"NLT",
                "cityCName":"那拉提",
                "cityEName":"NALATI",
                "cityFirstSpell":"nlt",
                "citySpell":"nalati"
            },
            {
                "airportCName":"鄂尔多斯伊金霍洛机场",
                "airportCode":"DSN",
                "cityCName":"鄂尔多斯",
                "cityEName":"Eerduosi",
                "cityFirstSpell":"eeds",
                "citySpell":"eerduosi"
            },
            {
                "airportCName":"永州零陵机场",
                "airportCode":"LLF",
                "cityCName":"永州",
                "cityEName":"Yongzhou",
                "cityFirstSpell":"yz",
                "citySpell":"yongzhou"
            },
            {
                "airportCName":"库车机场",
                "airportCode":"KCA",
                "cityCName":"库车",
                "cityEName":"Kuqa",
                "cityFirstSpell":"kc",
                "citySpell":"kuche"
            },
            {
                "airportCName":"连城机场",
                "airportCode":"LCX",
                "cityCName":"连城",
                "cityEName":"Liancheng",
                "cityFirstSpell":"lc",
                "citySpell":"liancheng"
            },
            {
                "airportCName":"德宏芒市机场",
                "airportCode":"LUM",
                "cityCName":"芒市",
                "cityEName":"Mangshi",
                "cityFirstSpell":"ms",
                "citySpell":"mangshi"
            },
            {
                "airportCName":"万州五桥机场",
                "airportCode":"WXN",
                "cityCName":"万州",
                "cityEName":"Wanxian",
                "cityFirstSpell":"wz",
                "citySpell":"wanzhou"
            },
            {
                "airportCName":"长海机场",
                "airportCode":"CNI",
                "cityCName":"长海",
                "cityEName":"Changhai",
                "cityFirstSpell":"zh",
                "citySpell":"changhai"
            },
            {
                "airportCName":"怀化芷江机场",
                "airportCode":"HJJ",
                "cityCName":"芷江",
                "cityEName":"Zhijiang",
                "cityFirstSpell":"zj",
                "citySpell":"zhijiang"
            },
            {
                "airportCName":"北京大兴国际机场",
                "airportCode":"PKX",
                "cityCName":"北京大兴",
                "cityEName":"Beijing",
                "cityFirstSpell":"bj",
                "citySpell":"beijing"
            },
            {
                "airportCName":"安庆天柱山机场",
                "airportCode":"AQG",
                "cityCName":"安庆",
                "cityEName":"Anqing",
                "cityFirstSpell":"aq",
                "citySpell":"anqing"
            },
            {
                "airportCName":"蚌埠机场",
                "airportCode":"BFU",
                "cityCName":"蚌埠",
                "cityEName":"Bengbu",
                "cityFirstSpell":"bb",
                "citySpell":"bangbu"
            },
            {
                "airportCName":"荆州沙市机场",
                "airportCode":"SHS",
                "cityCName":"荆州",
                "cityEName":"Jingzhou",
                "cityFirstSpell":"jz",
                "citySpell":"jingzhou"
            },
            {
                "airportCName":"武汉天河机场",
                "airportCode":"WUH",
                "cityCName":"武汉",
                "cityEName":"Wuhan",
                "cityFirstSpell":"wh",
                "citySpell":"wuhan"
            },
            {
                "airportCName":"三峡机场",
                "airportCode":"YIH",
                "cityCName":"宜昌",
                "cityEName":"Yichang",
                "cityFirstSpell":"yc",
                "citySpell":"yichang"
            },
            {
                "airportCName":"常德桃花源机场",
                "airportCode":"CGD",
                "cityCName":"常德",
                "cityEName":"Changde",
                "cityFirstSpell":"cd",
                "citySpell":"changde"
            },
            {
                "airportCName":"长沙黄花机场",
                "airportCode":"CSX",
                "cityCName":"长沙",
                "cityEName":"Changsha",
                "cityFirstSpell":"cs",
                "citySpell":"Changsha"
            },
            {
                "airportCName":"林芝机场",
                "airportCode":"LZY",
                "cityCName":"林芝",
                "cityEName":"Linzhi",
                "cityFirstSpell":"lz",
                "citySpell":"linzhi"
            },
            {
                "airportCName":"银川河东机场",
                "airportCode":"INC",
                "cityCName":"银川",
                "cityEName":"Yinchuan",
                "cityFirstSpell":"yc",
                "citySpell":"yinchuan"
            },
            {
                "airportCName":"格尔木机场",
                "airportCode":"GOQ",
                "cityCName":"格尔木",
                "cityEName":"Golmud",
                "cityFirstSpell":"gem",
                "citySpell":"geermu"
            },
            {
                "airportCName":"西宁曹家堡机场",
                "airportCode":"XNN",
                "cityCName":"西宁",
                "cityEName":"Xining",
                "cityFirstSpell":"xn",
                "citySpell":"xining"
            },
            {
                "airportCName":"阿克苏机场",
                "airportCode":"AKU",
                "cityCName":"阿克苏",
                "cityEName":"Aksu",
                "cityFirstSpell":"aks",
                "citySpell":"akesu"
            },
            {
                "airportCName":"阿勒泰机场",
                "airportCode":"AAT",
                "cityCName":"阿勒泰",
                "cityEName":"Altay",
                "cityFirstSpell":"alt",
                "citySpell":"aletai"
            },
            {
                "airportCName":"郑州新郑机场",
                "airportCode":"CGO",
                "cityCName":"郑州",
                "cityEName":"Zhengzhou",
                "cityFirstSpell":"zz",
                "citySpell":"zhengzhou"
            },
            {
                "airportCName":"赣州黄金机场",
                "airportCode":"KOW",
                "cityCName":"赣州",
                "cityEName":"Ganzhou",
                "cityFirstSpell":"gz",
                "citySpell":"ganzhou"
            },
            {
                "airportCName":"武夷山机场",
                "airportCode":"WUS",
                "cityCName":"武夷山",
                "cityEName":"Wuyishan",
                "cityFirstSpell":"wys",
                "citySpell":"wuyishan"
            },
            {
                "airportCName":"敦煌机场",
                "airportCode":"DNH",
                "cityCName":"敦煌",
                "cityEName":"Dunhuang",
                "cityFirstSpell":"dh",
                "citySpell":"dunhuang"
            },
            {
                "airportCName":"吉安机场",
                "airportCode":"KNC",
                "cityCName":"吉安",
                "cityEName":"Ji'an",
                "cityFirstSpell":"ja",
                "citySpell":"jian"
            },
            {
                "airportCName":"长白山",
                "airportCode":"NBS",
                "cityCName":"长白山",
                "cityEName":"Baishan",
                "cityFirstSpell":"zbs",
                "citySpell":"changbaishan"
            },
            {
                "airportCName":"长春龙嘉机场",
                "airportCode":"CGQ",
                "cityCName":"长春",
                "cityEName":"Changchun",
                "cityFirstSpell":"zc",
                "citySpell":"changchun"
            },
            {
                "airportCName":"吉林二台子机场",
                "airportCode":"JIL",
                "cityCName":"吉林",
                "cityEName":"Jilin",
                "cityFirstSpell":"jl",
                "citySpell":"jilin"
            },
            {
                "airportCName":"通化机场",
                "airportCode":"TNH",
                "cityCName":"通化",
                "cityEName":"Tonghua",
                "cityFirstSpell":"th",
                "citySpell":"tonghua"
            },
            {
                "airportCName":"延吉朝阳川机场",
                "airportCode":"YNJ",
                "cityCName":"延吉",
                "cityEName":"Yanji",
                "cityFirstSpell":"yj",
                "citySpell":"yanji"
            },
            {
                "airportCName":"常州奔牛机场",
                "airportCode":"CZX",
                "cityCName":"常州",
                "cityEName":"Changzhou",
                "cityFirstSpell":"cz",
                "citySpell":"changzhou"
            },
            {
                "airportCName":"淮安涟水机场",
                "airportCode":"HIA",
                "cityCName":"淮安",
                "cityEName":"Huaian",
                "cityFirstSpell":"ha",
                "citySpell":"huaian"
            },
            {
                "airportCName":"连云港机场",
                "airportCode":"LYG",
                "cityCName":"连云港",
                "cityEName":"Liangyungang",
                "cityFirstSpell":"lyg",
                "citySpell":"lianyungang"
            },
            {
                "airportCName":"南京禄口机场",
                "airportCode":"NKG",
                "cityCName":"南京",
                "cityEName":"Nanjing",
                "cityFirstSpell":"nj",
                "citySpell":"nanjing"
            },
            {
                "airportCName":"南通兴东机场",
                "airportCode":"NTG",
                "cityCName":"南通",
                "cityEName":"Nantong",
                "cityFirstSpell":"nt",
                "citySpell":"nantong"
            },
            {
                "airportCName":"苏州机场",
                "airportCode":"SZV",
                "cityCName":"苏州",
                "cityEName":"Suzhou",
                "cityFirstSpell":"sz",
                "citySpell":"suzhou"
            },
            {
                "airportCName":"无锡硕放机场",
                "airportCode":"WUX",
                "cityCName":"无锡",
                "cityEName":"Wuxi",
                "cityFirstSpell":"wx",
                "citySpell":"wuxi"
            },
            {
                "airportCName":"徐州观音机场",
                "airportCode":"XUZ",
                "cityCName":"徐州",
                "cityEName":"Xuzhou",
                "cityFirstSpell":"xz",
                "citySpell":"xuzhou"
            },
            {
                "airportCName":"江苏盐城南洋机场",
                "airportCode":"YNZ",
                "cityCName":"盐城",
                "cityEName":"Yancheng",
                "cityFirstSpell":"yc",
                "citySpell":"yancheng"
            },
            {
                "airportCName":"井冈山机场",
                "airportCode":"JGS",
                "cityCName":"井冈山",
                "cityEName":"Jinggangshan",
                "cityFirstSpell":"jgs",
                "citySpell":"jinggangshan"
            },
            {
                "airportCName":"景德镇罗家机场",
                "airportCode":"JDZ",
                "cityCName":"景德镇",
                "cityEName":"Jingdezhen",
                "cityFirstSpell":"jdz",
                "citySpell":"jingdezhen"
            },
            {
                "airportCName":"九江庐山机场",
                "airportCode":"JIU",
                "cityCName":"九江",
                "cityEName":"Jiujiang",
                "cityFirstSpell":"jj",
                "citySpell":"jiujiang"
            },
            {
                "airportCName":"南昌昌北机场",
                "airportCode":"KHN",
                "cityCName":"南昌",
                "cityEName":"Nanchang",
                "cityFirstSpell":"nc",
                "citySpell":"nanchang"
            },
            {
                "airportCName":"鞍山机场",
                "airportCode":"AOG",
                "cityCName":"鞍山",
                "cityEName":"Anshan",
                "cityFirstSpell":"as",
                "citySpell":"anshan"
            },
            {
                "airportCName":"丹东浪头机场",
                "airportCode":"DDG",
                "cityCName":"丹东",
                "cityEName":"Dandong",
                "cityFirstSpell":"dd",
                "citySpell":"dandong"
            },
            {
                "airportCName":"大连周水子国际机场",
                "airportCode":"DLC",
                "cityCName":"大连",
                "cityEName":"Dalian",
                "cityFirstSpell":"dl",
                "citySpell":"dalian"
            },
            {
                "airportCName":"内蒙古海拉尔东山机场",
                "airportCode":"HLD",
                "cityCName":"海拉尔",
                "cityEName":"Huludao",
                "cityFirstSpell":"hle",
                "citySpell":"hailaer"
            },
            {
                "airportCName":"锦州小岭子机场",
                "airportCode":"JNZ",
                "cityCName":"锦州",
                "cityEName":"Jinzhou",
                "cityFirstSpell":"jz",
                "citySpell":"jinzhou"
            },
            {
                "airportCName":"沈阳桃仙机场",
                "airportCode":"SHE",
                "cityCName":"沈阳",
                "cityEName":"Shenyang",
                "cityFirstSpell":"sy",
                "citySpell":"shenyang"
            },
            {
                "airportCName":"兴城机场",
                "airportCode":"XEN",
                "cityCName":"兴城",
                "cityEName":"Xingcheng",
                "cityFirstSpell":"xc",
                "citySpell":"xingcheng"
            },
            {
                "airportCName":"东营机场",
                "airportCode":"DOY",
                "cityCName":"东营",
                "cityEName":"Dongying",
                "cityFirstSpell":"dy",
                "citySpell":"dongying"
            },
            {
                "airportCName":"济南机场",
                "airportCode":"TNA",
                "cityCName":"济南",
                "cityEName":"Jinan",
                "cityFirstSpell":"jn",
                "citySpell":"jinan"
            },
            {
                "airportCName":"济宁机场",
                "airportCode":"JNG",
                "cityCName":"济宁",
                "cityEName":"Jining",
                "cityFirstSpell":"jn",
                "citySpell":"jining"
            },
            {
                "airportCName":"临沂机场",
                "airportCode":"LYI",
                "cityCName":"临沂",
                "cityEName":"Linyi",
                "cityFirstSpell":"ly",
                "citySpell":"linyi"
            },
            {
                "airportCName":"北京首都国际机场",
                "airportCode":"PEK",
                "cityCName":"北京首都",
                "cityEName":"beijing",
                "cityFirstSpell":"bj",
                "citySpell":"beijing"
            },
            {
                "airportCName":"青岛流亭机场",
                "airportCode":"TAO",
                "cityCName":"青岛",
                "cityEName":"Qingdao",
                "cityFirstSpell":"qd",
                "citySpell":"qingdao"
            },
            {
                "airportCName":"酒泉机场",
                "airportCode":"CHW",
                "cityCName":"酒泉",
                "cityEName":"Jiuquan",
                "cityFirstSpell":"jq",
                "citySpell":"jiuquan"
            },
            {
                "airportCName":"嘉峪关机场",
                "airportCode":"JGN",
                "cityCName":"嘉峪关",
                "cityEName":"Jiayuguan",
                "cityFirstSpell":"jyg",
                "citySpell":"jiayuguan"
            },
            {
                "airportCName":"兰州中川机场",
                "airportCode":"LHW",
                "cityCName":"兰州",
                "cityEName":"Lanzhou",
                "cityFirstSpell":"lz",
                "citySpell":"lanzhou"
            },
            {
                "airportCName":"庆阳机场",
                "airportCode":"IQN",
                "cityCName":"庆阳",
                "cityEName":"Qingyang",
                "cityFirstSpell":"qy",
                "citySpell":"qingyang"
            },
            {
                "airportCName":"蓬莱机场",
                "airportCode":"PNJ",
                "cityCName":"蓬莱",
                "cityEName":"Penglai",
                "cityFirstSpell":"pl",
                "citySpell":"penglai"
            },
            {
                "airportCName":"威海文登大水泊机场",
                "airportCode":"WEH",
                "cityCName":"威海",
                "cityEName":"Wendeng",
                "cityFirstSpell":"wh",
                "citySpell":"weihai"
            },
            {
                "airportCName":"潍坊机场",
                "airportCode":"WEF",
                "cityCName":"潍坊",
                "cityEName":"Weifang",
                "cityFirstSpell":"wf",
                "citySpell":"weifang"
            },
            {
                "airportCName":"烟台蓬莱国际机场",
                "airportCode":"YNT",
                "cityCName":"烟台",
                "cityEName":"Yantai",
                "cityFirstSpell":"yt",
                "citySpell":"yantai"
            },
            {
                "airportCName":"长治机场",
                "airportCode":"CIH",
                "cityCName":"长治",
                "cityEName":"Changzhi",
                "cityFirstSpell":"zz",
                "citySpell":"changzhi"
            },
            {
                "airportCName":"大同机场",
                "airportCode":"DAT",
                "cityCName":"大同",
                "cityEName":"Datong",
                "cityFirstSpell":"dt",
                "citySpell":"datong"
            },
            {
                "airportCName":"太原武宿机场",
                "airportCode":"TYN",
                "cityCName":"太原",
                "cityEName":"Taiyuan",
                "cityFirstSpell":"ty",
                "citySpell":"taiyuan"
            },
            {
                "airportCName":"五台山机场",
                "airportCode":"WUT",
                "cityCName":"五台山",
                "cityEName":"Wutaishan",
                "cityFirstSpell":"wts",
                "citySpell":"wutaishan"
            },
            {
                "airportCName":"运城关公机场",
                "airportCode":"YCU",
                "cityCName":"运城",
                "cityEName":"Yuncheng",
                "cityFirstSpell":"yc",
                "citySpell":"yuncheng"
            },
            {
                "airportCName":"安康机场",
                "airportCode":"AKA",
                "cityCName":"安康",
                "cityEName":"Ankang",
                "cityFirstSpell":"ak",
                "citySpell":"ankang"
            },
            {
                "airportCName":"西安咸阳国际机场",
                "airportCode":"XIY",
                "cityCName":"西安/咸阳",
                "cityEName":"Xi'an",
                "cityFirstSpell":"xa/xy",
                "citySpell":"xi'an"
            },
            {
                "airportCName":"延安二十里铺机场",
                "airportCode":"ENY",
                "cityCName":"延安",
                "cityEName":"Yanan",
                "cityFirstSpell":"ya",
                "citySpell":"yanan"
            },
            {
                "airportCName":"榆林机场",
                "airportCode":"UYN",
                "cityCName":"榆林",
                "cityEName":"Yulin",
                "cityFirstSpell":"yl",
                "citySpell":"yulin"
            },
            {
                "airportCName":"上海浦东机场",
                "airportCode":"PVG",
                "cityCName":"上海浦东",
                "cityEName":"Shanghai",
                "cityFirstSpell":"sh",
                "citySpell":"shanghai"
            },
            {
                "airportCName":"成都双流国际机场",
                "airportCode":"CTU",
                "cityCName":"成都",
                "cityEName":"Chengdu",
                "cityFirstSpell":"cd",
                "citySpell":"chengdou"
            },
            {
                "airportCName":"达县机场",
                "airportCode":"DAX",
                "cityCName":"达县",
                "cityEName":"Dazhou",
                "cityFirstSpell":"dx",
                "citySpell":"daxian"
            },
            {
                "airportCName":"广汉机场",
                "airportCode":"GHN",
                "cityCName":"广汉",
                "cityEName":"Guanghan",
                "cityFirstSpell":"gh",
                "citySpell":"guanghan"
            },
            {
                "airportCName":"广元机场",
                "airportCode":"GYS",
                "cityCName":"广元",
                "cityEName":"Guangyuan",
                "cityFirstSpell":"gy",
                "citySpell":"guangyuan"
            },
            {
                "airportCName":"九寨沟机场",
                "airportCode":"JZH",
                "cityCName":"九寨沟",
                "cityEName":"Jiuzhaigou",
                "cityFirstSpell":"jzg",
                "citySpell":"jiuzhaigou"
            },
            {
                "airportCName":"泸州机场",
                "airportCode":"LZO",
                "cityCName":"泸州",
                "cityEName":"Luzhou",
                "cityFirstSpell":"lz",
                "citySpell":"luzhou"
            },
            {
                "airportCName":"绵阳南郊机场",
                "airportCode":"MIG",
                "cityCName":"绵阳",
                "cityEName":"Mianyang",
                "cityFirstSpell":"my",
                "citySpell":"mianyang"
            },
            {
                "airportCName":"南充机场",
                "airportCode":"NAO",
                "cityCName":"南充",
                "cityEName":"Nanchong",
                "cityFirstSpell":"nc",
                "citySpell":"nanchong"
            },
            {
                "airportCName":"攀枝花保安营机场",
                "airportCode":"PZI",
                "cityCName":"攀枝花",
                "cityEName":"Panzhihua",
                "cityFirstSpell":"pzh",
                "citySpell":"panzhihua"
            },
            {
                "airportCName":"西昌机场",
                "airportCode":"XIC",
                "cityCName":"西昌",
                "cityEName":"Xichang",
                "cityFirstSpell":"xc",
                "citySpell":"xichang"
            },
            {
                "airportCName":"宜宾菜坝机场",
                "airportCode":"YBP",
                "cityCName":"宜宾",
                "cityEName":"Yibin",
                "cityFirstSpell":"yb",
                "citySpell":"yibin"
            },
            {
                "airportCName":"滨海国际机场",
                "airportCode":"TSN",
                "cityCName":"天津",
                "cityEName":"Tianjin",
                "cityFirstSpell":"tj",
                "citySpell":"tianjin"
            },
            {
                "airportCName":"昌都邦达机场",
                "airportCode":"BPX",
                "cityCName":"昌都",
                "cityEName":"Changdu",
                "cityFirstSpell":"cd",
                "citySpell":"changdou"
            },
            {
                "airportCName":"上海虹桥机场",
                "airportCode":"SHA",
                "cityCName":"上海虹桥",
                "cityEName":"Shanghai",
                "cityFirstSpell":"sh",
                "citySpell":"shanghai"
            },
            {
                "airportCName":"且末机场",
                "airportCode":"IQM",
                "cityCName":"且末",
                "cityEName":"Qiemo",
                "cityFirstSpell":"qm",
                "citySpell":"qiemo"
            },
            {
                "airportCName":"齐齐哈尔机场",
                "airportCode":"NDG",
                "cityCName":"齐齐哈尔",
                "cityEName":"QiqIihar",
                "cityFirstSpell":"qqhe",
                "citySpell":"qiqihaer"
            },
            {
                "airportCName":"三亚凤凰机场",
                "airportCode":"SYX",
                "cityCName":"三亚",
                "cityEName":"Sanya",
                "cityFirstSpell":"sy",
                "citySpell":"sanya"
            },
            {
                "airportCName":"合肥新桥国际机场",
                "airportCode":"HFE",
                "cityCName":"合肥",
                "cityEName":"Hefei",
                "cityFirstSpell":"hf",
                "citySpell":"hefei"
            },
            {
                "airportCName":"阜阳机场",
                "airportCode":"FUG",
                "cityCName":"阜阳",
                "cityEName":"Fuyang",
                "cityFirstSpell":"fy",
                "citySpell":"fuyang"
            },
            {
                "airportCName":"黄山屯溪机场",
                "airportCode":"TXN",
                "cityCName":"黄山",
                "cityEName":"Huangshan",
                "cityFirstSpell":"hs",
                "citySpell":"huangshan"
            },
            {
                "airportCName":"芜湖机场",
                "airportCode":"WHU",
                "cityCName":"芜湖",
                "cityEName":"Wuhu",
                "cityFirstSpell":"wh",
                "citySpell":"wuhu"
            },
            {
                "airportCName":"佛山机场",
                "airportCode":"FUO",
                "cityCName":"佛山",
                "cityEName":"Fuoshan",
                "cityFirstSpell":"fs",
                "citySpell":"foshan"
            },
            {
                "airportCName":"广州白云机场",
                "airportCode":"CAN",
                "cityCName":"广州",
                "cityEName":"Guangzhou",
                "cityFirstSpell":"gz",
                "citySpell":"guangzhou"
            },
            {
                "airportCName":"惠州机场",
                "airportCode":"HUZ",
                "cityCName":"惠州",
                "cityEName":"Huizhou",
                "cityFirstSpell":"hz",
                "citySpell":"huizhou"
            },
            {
                "airportCName":"揭阳机场",
                "airportCode":"SWA",
                "cityCName":"揭阳",
                "cityEName":"JIEYANG",
                "cityFirstSpell":"jy",
                "citySpell":"jieyang"
            },
            {
                "airportCName":"深圳宝安国际机场",
                "airportCode":"SZX",
                "cityCName":"深圳",
                "cityEName":"Shenzhen",
                "cityFirstSpell":"sz",
                "citySpell":"shenzhen"
            },
            {
                "airportCName":"金湾机场",
                "airportCode":"ZUH",
                "cityCName":"珠海",
                "cityEName":"Zhuhai",
                "cityFirstSpell":"zh",
                "citySpell":"zhuhai"
            },
            {
                "airportCName":"湛江机场",
                "airportCode":"ZHA",
                "cityCName":"湛江",
                "cityEName":"Zhanjiang",
                "cityFirstSpell":"zj",
                "citySpell":"zhanjiang"
            },
            {
                "airportCName":"北海福城机场",
                "airportCode":"BHY",
                "cityCName":"北海",
                "cityEName":"Beihai",
                "cityFirstSpell":"bh",
                "citySpell":"beihai"
            },
            {
                "airportCName":"百色机场",
                "airportCode":"AEB",
                "cityCName":"百色",
                "cityEName":"BOSE",
                "cityFirstSpell":"bs",
                "citySpell":"baise"
            },
            {
                "airportCName":"桂林两江机场",
                "airportCode":"KWL",
                "cityCName":"桂林",
                "cityEName":"Guilin",
                "cityFirstSpell":"gl",
                "citySpell":"guilin"
            },
            {
                "airportCName":"黎平机场",
                "airportCode":"HZH",
                "cityCName":"黎平",
                "cityEName":"Hezhou",
                "cityFirstSpell":"lp",
                "citySpell":"liping"
            },
            {
                "airportCName":"柳州白莲机场",
                "airportCode":"LZH",
                "cityCName":"柳州",
                "cityEName":"Liuzhou",
                "cityFirstSpell":"lz",
                "citySpell":"liuzhou"
            },
            {
                "airportCName":"南宁吴圩机场",
                "airportCode":"NNG",
                "cityCName":"南宁",
                "cityEName":"Nanning",
                "cityFirstSpell":"nn",
                "citySpell":"nanning"
            },
            {
                "airportCName":"塔城机场",
                "airportCode":"TCG",
                "cityCName":"塔城",
                "cityEName":"Tacheng",
                "cityFirstSpell":"tc",
                "citySpell":"tacheng"
            },
            {
                "airportCName":"乌鲁木齐地窝堡国际机场",
                "airportCode":"URC",
                "cityCName":"乌鲁木齐",
                "cityEName":"WUrumqi",
                "cityFirstSpell":"wlmq",
                "citySpell":"wulumuqi"
            },
            {
                "airportCName":"伊宁机场",
                "airportCode":"YIN",
                "cityCName":"伊宁",
                "cityEName":"Yining",
                "cityFirstSpell":"yn",
                "citySpell":"yining"
            },
            {
                "airportCName":"保山云瑞机场",
                "airportCode":"BSD",
                "cityCName":"保山",
                "cityEName":"Baoshan",
                "cityFirstSpell":"bs",
                "citySpell":"baoshan"
            },
            {
                "airportCName":"大理机场",
                "airportCode":"DLU",
                "cityCName":"大理",
                "cityEName":"Dali",
                "cityFirstSpell":"dl",
                "citySpell":"dali"
            },
            {
                "airportCName":"香格里拉机场",
                "airportCode":"DIG",
                "cityCName":"迪庆",
                "cityEName":"Diqing",
                "cityFirstSpell":"dq",
                "citySpell":"diqing"
            },
            {
                "airportCName":"昆明长水国际机场",
                "airportCode":"KMG",
                "cityCName":"昆明",
                "cityEName":"Kunming",
                "cityFirstSpell":"km",
                "citySpell":"kunming"
            },
            {
                "airportCName":"临沧机场",
                "airportCode":"LNJ",
                "cityCName":"临沧",
                "cityEName":"Lincang",
                "cityFirstSpell":"lc",
                "citySpell":"lincang"
            },
            {
                "airportCName":"丽江三义机场",
                "airportCode":"LJG",
                "cityCName":"丽江",
                "cityEName":"Lijiang",
                "cityFirstSpell":"lj",
                "citySpell":"lijiang"
            },
            {
                "airportCName":"思茅机场",
                "airportCode":"SYM",
                "cityCName":"思茅",
                "cityEName":"Simao",
                "cityFirstSpell":"sm",
                "citySpell":"simao"
            },
            {
                "airportCName":"景洪(西双版纳)机场",
                "airportCode":"JHG",
                "cityCName":"西双版纳",
                "cityEName":"XSBN",
                "cityFirstSpell":"xsbn",
                "citySpell":"xishuangbanna"
            },
            {
                "airportCName":"昭通机场",
                "airportCode":"ZAT",
                "cityCName":"昭通",
                "cityEName":"Zhaotong",
                "cityFirstSpell":"zt",
                "citySpell":"zhaotong"
            },
            {
                "airportCName":"台州黄岩机场",
                "airportCode":"HYN",
                "cityCName":"台州",
                "cityEName":"TAIZHOU",
                "cityFirstSpell":"tz",
                "citySpell":"taizhou"
            },
            {
                "airportCName":"杭州萧山国际机场",
                "airportCode":"HGH",
                "cityCName":"杭州",
                "cityEName":"Hangzhou",
                "cityFirstSpell":"hz",
                "citySpell":"hangzhou"
            },
            {
                "airportCName":"宁波栎社机场",
                "airportCode":"NGB",
                "cityCName":"宁波",
                "cityEName":"Ningbo",
                "cityFirstSpell":"nb",
                "citySpell":"ningbo"
            },
            {
                "airportCName":"衢州机场",
                "airportCode":"JUZ",
                "cityCName":"衢州",
                "cityEName":"Quzhou",
                "cityFirstSpell":"qz",
                "citySpell":"quzhou"
            },
            {
                "airportCName":"温州龙湾国际机场",
                "airportCode":"WNZ",
                "cityCName":"温州",
                "cityEName":"Wenzhou",
                "cityFirstSpell":"wz",
                "citySpell":"wenzhou"
            },
            {
                "airportCName":"义乌机场",
                "airportCode":"YIW",
                "cityCName":"义乌",
                "cityEName":"Yiwu",
                "cityFirstSpell":"yw",
                "citySpell":"yiwu"
            },
            {
                "airportCName":"重庆江北国际机场",
                "airportCode":"CKG",
                "cityCName":"重庆",
                "cityEName":"Chongqing",
                "cityFirstSpell":"zq",
                "citySpell":"zhongqing"
            },
            {
                "airportCName":"福州长乐机场",
                "airportCode":"FOC",
                "cityCName":"福州",
                "cityEName":"Fuzhou",
                "cityFirstSpell":"fz",
                "citySpell":"fuzhou"
            },
            {
                "airportCName":"泉州机场",
                "airportCode":"JJN",
                "cityCName":"泉州晋江",
                "cityEName":"Quanzhou",
                "cityFirstSpell":"qzjj",
                "citySpell":"quanzhoujinjiang"
            },
            {
                "airportCName":"厦门高崎机场",
                "airportCode":"XMN",
                "cityCName":"厦门",
                "cityEName":"Xiamen",
                "cityFirstSpell":"sm",
                "citySpell":"shamen"
            },
            {
                "airportCName":"包头机场",
                "airportCode":"BAV",
                "cityCName":"包头",
                "cityEName":"Baotou",
                "cityFirstSpell":"bt",
                "citySpell":"baotou"
            },
            {
                "airportCName":"赤峰机场",
                "airportCode":"CIF",
                "cityCName":"赤峰",
                "cityEName":"Chifeng",
                "cityFirstSpell":"cf",
                "citySpell":"chifeng"
            },
            {
                "airportCName":"满洲里机场",
                "airportCode":"NZH",
                "cityCName":"满洲里",
                "cityEName":"Manzhouli",
                "cityFirstSpell":"mzl",
                "citySpell":"manzhouli"
            },
            {
                "airportCName":"通辽机场",
                "airportCode":"TGO",
                "cityCName":"通辽",
                "cityEName":"Tongliao",
                "cityFirstSpell":"tl",
                "citySpell":"tongliao"
            },
            {
                "airportCName":"乌海机场",
                "airportCode":"WUA",
                "cityCName":"乌海",
                "cityEName":"Wuhai",
                "cityFirstSpell":"wh",
                "citySpell":"wuhai"
            },
            {
                "airportCName":"乌兰浩特机场",
                "airportCode":"HLH",
                "cityCName":"乌兰浩特",
                "cityEName":"WUlanhot",
                "cityFirstSpell":"wlht",
                "citySpell":"wulanhaote"
            },
            {
                "airportCName":"锡林浩特机场",
                "airportCode":"XIL",
                "cityCName":"锡林浩特",
                "cityEName":"Xilinhot",
                "cityFirstSpell":"xlht",
                "citySpell":"xilinhaote"
            },
            {
                "airportCName":"贡嘎机场",
                "airportCode":"LXA",
                "cityCName":"拉萨",
                "cityEName":"LaSa",
                "cityFirstSpell":"ls",
                "citySpell":"lasa"
            },
            {
                "airportCName":"衡阳机场",
                "airportCode":"HNY",
                "cityCName":"衡阳",
                "cityEName":"Hengyang",
                "cityFirstSpell":"hy",
                "citySpell":"hengyang"
            },
            {
                "airportCName":"舟山机场",
                "airportCode":"HSN",
                "cityCName":"舟山",
                "cityEName":"Zhoushan",
                "cityFirstSpell":"zs",
                "citySpell":"zhoushan"
            },
            {
                "airportCName":"汉中西关机场",
                "airportCode":"HZG",
                "cityCName":"汉中",
                "cityEName":"Hanzhong",
                "cityFirstSpell":"hz",
                "citySpell":"hanzhong"
            },
            {
                "airportCName":"梅县机场",
                "airportCode":"MXZ",
                "cityCName":"梅县",
                "cityEName":"Meixian",
                "cityFirstSpell":"mx",
                "citySpell":"meixian"
            },
            {
                "airportCName":"荷花机场",
                "airportCode":"DYG",
                "cityCName":"张家界",
                "cityEName":"Zhangjiajie",
                "cityFirstSpell":"zjj",
                "citySpell":"zhangjiajie"
            },
            {
                "airportCName":"富蕴机场",
                "airportCode":"FYN",
                "cityCName":"富蕴",
                "cityEName":"FuYun",
                "cityFirstSpell":"fy",
                "citySpell":"fuyun"
            },
            {
                "airportCName":"刘集机场",
                "airportCode":"XFN",
                "cityCName":"襄樊",
                "cityEName":"Xiangfan",
                "cityFirstSpell":"xf",
                "citySpell":"xiangfan"
            },
            {
                "airportCName":"呼和浩特白塔机场",
                "airportCode":"HET",
                "cityCName":"呼和浩特",
                "cityEName":"HoHeHaoTe",
                "cityFirstSpell":"hhht",
                "citySpell":"huhehaote"
            },
            {
                "airportCName":"和田机场",
                "airportCode":"HTN",
                "cityCName":"和田",
                "cityEName":"Hotan",
                "cityFirstSpell":"ht",
                "citySpell":"hetian"
            },
            {
                "airportCName":"库尔勒机场",
                "airportCode":"KRL",
                "cityCName":"库尔勒",
                "cityEName":"Korla",
                "cityFirstSpell":"kel",
                "citySpell":"kuerle"
            },
            {
                "airportCName":"克拉玛依机场",
                "airportCode":"KRY",
                "cityCName":"克拉玛依",
                "cityEName":"Kalamayi",
                "cityFirstSpell":"klmy",
                "citySpell":"kelamayi"
            },
            {
                "airportCName":"喀什机场",
                "airportCode":"KHG",
                "cityCName":"喀什",
                "cityEName":"Kashi",
                "cityFirstSpell":"ks",
                "citySpell":"kashen"
            },
            {
                "airportCName":"唐山机场",
                "airportCode":"TVS",
                "cityCName":"唐山",
                "cityEName":"Tangshan",
                "cityFirstSpell":"ts",
                "citySpell":"tangshan"
            },
            {
                "airportCName":"毕节飞雄机场",
                "airportCode":"BFJ",
                "cityCName":"毕节",
                "cityEName":"BIJIE",
                "cityFirstSpell":"bj",
                "citySpell":"bijie"
            },
            {
                "airportCName":"黑河机场",
                "airportCode":"HEK",
                "cityCName":"黑河",
                "cityEName":"Heihe",
                "cityFirstSpell":"hh",
                "citySpell":"heihe"
            },
            {
                "airportCName":"天水机场",
                "airportCode":"THQ",
                "cityCName":"天水",
                "cityEName":"Tianshui",
                "cityFirstSpell":"ts",
                "citySpell":"tianshui"
            },
            {
                "airportCName":"金川",
                "airportCode":"JIC",
                "cityCName":"金昌",
                "cityEName":"jinchang",
                "cityFirstSpell":"jc",
                "citySpell":"jinchang"
            },
            {
                "airportCName":"巴彦淖尔机场",
                "airportCode":"RLK",
                "cityCName":"巴彦淖尔",
                "cityEName":"bayanzhuoer",
                "cityFirstSpell":"byne",
                "citySpell":"bayannaoer"
            },
            {
                "airportCName":"新疆博乐机场",
                "airportCode":"BPL",
                "cityCName":"博乐",
                "cityEName":"bole",
                "cityFirstSpell":"bl",
                "citySpell":"bole"
            },
            {
                "airportCName":"宜春明月山机场",
                "airportCode":"YIC",
                "cityCName":"宜春",
                "cityEName":"yichun",
                "cityFirstSpell":"yc",
                "citySpell":"yichun"
            },
            {
                "airportCName":"神农架机场",
                "airportCode":"HPG",
                "cityCName":"湖北神农架",
                "cityEName":"shennongjia",
                "cityFirstSpell":"hbsnj",
                "citySpell":"hubeishennongjia"
            },
            {
                "airportCName":"博鳌机场",
                "airportCode":"BAR",
                "cityCName":"琼海",
                "cityEName":"Qionghai",
                "cityFirstSpell":"qh",
                "citySpell":"qionghai"
            },
            {
                "airportCName":"邢台机场",
                "airportCode":"XTW",
                "cityCName":"邢台",
                "cityEName":"Xingtai airport",
                "cityFirstSpell":"xt",
                "citySpell":"xingtai"
            },
            {
                "airportCName":"十堰武当山机场",
                "airportCode":"WDS",
                "cityCName":"十堰",
                "cityEName":"SHIYAN",
                "cityFirstSpell":"sy",
                "citySpell":"shiyan"
            },
            {
                "airportCName":"日照机场",
                "airportCode":"RIZ",
                "cityCName":"日照",
                "cityEName":"Rizhao airport",
                "cityFirstSpell":"rz",
                "citySpell":"rizhao"
            },
            {
                "airportCName":"秦皇岛北戴河机场",
                "airportCode":"BPE",
                "cityCName":"秦皇岛北戴河",
                "cityEName":"QINHUANGDAO BEIDAHE AIRPORT",
                "cityFirstSpell":"qhdbdh",
                "citySpell":"qinhuangdaobeidaihe"
            },
            {
                "airportCName":"阿拉善右旗巴丹吉林机场",
                "airportCode":"RHT",
                "cityCName":"阿拉善右旗",
                "cityEName":"BADANJILIN",
                "cityFirstSpell":"alsyq",
                "citySpell":"alashanyouqi"
            },
            {
                "airportCName":"额济纳旗桃来机场",
                "airportCode":"EJN",
                "cityCName":"额济纳旗",
                "cityEName":"ERJINA",
                "cityFirstSpell":"ejnq",
                "citySpell":"ejinaqi"
            },
            {
                "airportCName":"吐鲁番",
                "airportCode":"TLQ",
                "cityCName":"吐鲁番交河机场",
                "cityEName":"TULUFAN",
                "cityFirstSpell":"tlfjhjc",
                "citySpell":"tulufanjiaohejichang"
            },
            {
                "airportCName":"哈密机场",
                "airportCode":"HMI",
                "cityCName":"哈密",
                "cityEName":"HAMI",
                "cityFirstSpell":"hmjc",
                "citySpell":"hamijichang"
            },
            {
                "airportCName":"张掖甘州机场",
                "airportCode":"YZY",
                "cityCName":"张掖",
                "cityEName":"ZHANGYE",
                "cityFirstSpell":"zy",
                "citySpell":"zhangye"
            },
            {
                "airportCName":"稻城亚丁机场",
                "airportCode":"DCY",
                "cityCName":"稻城",
                "cityEName":"DAOCHENG",
                "cityFirstSpell":"dc",
                "citySpell":"daocheng"
            },
            {
                "airportCName":"朝阳机场",
                "airportCode":"CHG",
                "cityCName":"朝阳",
                "cityEName":"CHAOYANG",
                "cityFirstSpell":"cy",
                "citySpell":"chaoyang"
            },
            {
                "airportCName":"凯里黄平机场",
                "airportCode":"KJH",
                "cityCName":"黔东南",
                "cityEName":"KAILI",
                "cityFirstSpell":"qdn",
                "citySpell":"qiandongnan"
            },
            {
                "airportCName":"兴义机场",
                "airportCode":"ACX",
                "cityCName":"黔西南",
                "cityEName":"XINGYI",
                "cityFirstSpell":"qxn",
                "citySpell":"qianxinan"
            },
            {
                "airportCName":"六盘山机场",
                "airportCode":"GYU",
                "cityCName":"宁夏固原",
                "cityEName":"guyuan",
                "cityFirstSpell":"nxgy",
                "citySpell":"ningxiaguyuan"
            },
            {
                "airportCName":"三明",
                "airportCode":"SQJ",
                "cityCName":"三明沙县机场",
                "cityEName":"SANMINGSHA",
                "cityFirstSpell":"smsxjc",
                "citySpell":"sanmingshaxianjichang"
            },
            {
                "airportCName":"吕梁机场",
                "airportCode":"LLV",
                "cityCName":"吕梁",
                "cityEName":"Lvliang",
                "cityFirstSpell":"ll",
                "citySpell":"lu:liang"
            },
            {
                "airportCName":"18荔波机场",
                "airportCode":"LLB",
                "cityCName":"南端荔波县",
                "cityEName":"Libo Airport",
                "cityFirstSpell":"ndlbx",
                "citySpell":"nanduanliboxian"
            },
            {
                "airportCName":"泸沽湖机场",
                "airportCode":"NLH",
                "cityCName":"泸沽湖",
                "cityEName":"Luguhuzhen",
                "cityFirstSpell":"lgh",
                "citySpell":"luguhu"
            },
            {
                "airportCName":"日喀则和平机场",
                "airportCode":"RKZ",
                "cityCName":"日喀则",
                "cityEName":"RIKAZE",
                "cityFirstSpell":"rkz",
                "citySpell":"rikaze"
            },
            {
                "airportCName":"营口机场",
                "airportCode":"YKH",
                "cityCName":"营口",
                "cityEName":"YINGKOU LANQI AIRPORT",
                "cityFirstSpell":"yk",
                "citySpell":"yingkou"
            },
            {
                "airportCName":"池州九华山机场",
                "airportCode":"JUH",
                "cityCName":"安徽",
                "cityEName":"ANHUI",
                "cityFirstSpell":"ah",
                "citySpell":"anhui"
            },
            {
                "airportCName":"阿拉善左旗巴彦浩特机场",
                "airportCode":"AXF",
                "cityCName":"阿拉善左旗",
                "cityEName":"BAYANHAOTE",
                "cityFirstSpell":"alszq",
                "citySpell":"alashanzuoqi"
            },
            {
                "airportCName":"阿坝红原机场",
                "airportCode":"AHJ",
                "cityCName":"红原",
                "cityEName":"Aba Hongyuan Airport",
                "cityFirstSpell":"hy",
                "citySpell":"hongyuan"
            },
            {
                "airportCName":"泰州机场",
                "airportCode":"YTY",
                "cityCName":"扬州",
                "cityEName":"yangzhou",
                "cityFirstSpell":"yz",
                "citySpell":"yangzhou"
            },
            {
                "airportCName":"腾冲驼峰机场",
                "airportCode":"TCZ",
                "cityCName":"腾冲",
                "cityEName":"Tengchong",
                "cityFirstSpell":"tc",
                "citySpell":"tengchong"
            },
            {
                "airportCName":"漠河机场",
                "airportCode":"OHE",
                "cityCName":"漠河",
                "cityEName":"MoHe",
                "cityFirstSpell":"mh",
                "citySpell":"mohe"
            },
            {
                "airportCName":"中卫香山机场",
                "airportCode":"ZHY",
                "cityCName":"中卫",
                "cityEName":"Zhongwei",
                "cityFirstSpell":"zw",
                "citySpell":"zhongwei"
            },
            {
                "airportCName":"喀纳斯机场",
                "airportCode":"KJI",
                "cityCName":"喀纳斯",
                "cityEName":"KANASI",
                "cityFirstSpell":"kns",
                "citySpell":"kanasi"
            },
            {
                "airportCName":"姜营机场",
                "airportCode":"NNY",
                "cityCName":"南阳",
                "cityEName":"NanYang",
                "cityFirstSpell":"ny",
                "citySpell":"nanyang"
            },
            {
                "airportCName":"大庆萨尔图机场",
                "airportCode":"DQA",
                "cityCName":"大庆",
                "cityEName":"Daqing",
                "cityFirstSpell":"dq",
                "citySpell":"daqing"
            },
            {
                "airportCName":"二连浩特机场",
                "airportCode":"ERL",
                "cityCName":"二连浩特",
                "cityEName":"Erlianhaote",
                "cityFirstSpell":"elht",
                "citySpell":"erlianhaote"
            },
            {
                "airportCName":"康定机场",
                "airportCode":"KGT",
                "cityCName":"康定",
                "cityEName":"Kangding",
                "cityFirstSpell":"kd",
                "citySpell":"kangding"
            },
            {
                "airportCName":"黔江机场",
                "airportCode":"JIQ",
                "cityCName":"黔江",
                "cityEName":"Qianjiang",
                "cityFirstSpell":"qj",
                "citySpell":"qianjiang"
            },
            {
                "airportCName":"兴凯湖机场",
                "airportCode":"JXA",
                "cityCName":"鸡西",
                "cityEName":"Jixi",
                "cityFirstSpell":"jx",
                "citySpell":"jixi"
            },
            {
                "airportCName":"伊春机场",
                "airportCode":"LDS",
                "cityCName":"伊春",
                "cityEName":"Yichun",
                "cityFirstSpell":"yc",
                "citySpell":"yichun"
            },
            {
                "airportCName":"玉树机场",
                "airportCode":"YUS",
                "cityCName":"玉树",
                "cityEName":"YuShu",
                "cityFirstSpell":"ys",
                "citySpell":"yushu"
            },
            {
                "airportCName":"云南文山普者黑机场",
                "airportCode":"WNH",
                "cityCName":"文山",
                "cityEName":"PUZHEHEI",
                "cityFirstSpell":"ws",
                "citySpell":"wenshan"
            },
            {
                "airportCName":"兰州中川国际机场",
                "airportCode":"ZGC",
                "cityCName":"兰州",
                "cityEName":"Lanzhou",
                "cityFirstSpell":"lz",
                "citySpell":"zhongchuan"
            },
            {
                "airportCName":"元谋机场",
                "airportCode":"YUA",
                "cityCName":"元谋",
                "cityEName":"YUANMOU",
                "cityFirstSpell":"ym",
                "citySpell":"yuanmou"
            },
            {
                "airportCName":"兴宁机场",
                "airportCode":"XIN",
                "cityCName":"兴宁",
                "cityEName":"XINGNING",
                "cityFirstSpell":"xn",
                "citySpell":"xingning"
            },
            {
                "airportCName":"中卫沙坡头机场",
                "airportCode":"THY",
                "cityCName":"中卫",
                "cityEName":"Zhongwei",
                "cityFirstSpell":"zw",
                "citySpell":"zhongwei"
            },
            {
                "airportCName":"膳善机场",
                "airportCode":"SXJ",
                "cityCName":"膳善",
                "cityEName":"SHANSHAN",
                "cityFirstSpell":"ss",
                "citySpell":"shanshan"
            },
            {
                "airportCName":"山海关机场",
                "airportCode":"SHF",
                "cityCName":"山海关",
                "cityEName":"SHANHAIGUAN",
                "cityFirstSpell":"shg",
                "citySpell":"shanhaiguan"
            },
            {
                "airportCName":"西安西关机场",
                "airportCode":"SIA",
                "cityCName":"西安",
                "cityEName":"XI AN",
                "cityFirstSpell":"xa",
                "citySpell":"xi'an"
            },
            {
                "airportCName":"嫩江机场",
                "airportCode":"NNN",
                "cityCName":"嫩江",
                "cityEName":"NENJIANG",
                "cityFirstSpell":"nj",
                "citySpell":"NENJIANG"
            },
            {
                "airportCName":"庐山机场",
                "airportCode":"LUZ",
                "cityCName":"庐山",
                "cityEName":"LUSHAN",
                "cityFirstSpell":"ls",
                "citySpell":"LUSHAN"
            },
            {
                "airportCName":"光化机场",
                "airportCode":"LHK",
                "cityCName":"光化",
                "cityEName":"GUANGHUA",
                "cityFirstSpell":"gh",
                "citySpell":"guanghua"
            },
            {
                "airportCName":"梁平机场",
                "airportCode":"LIA",
                "cityCName":"梁平",
                "cityEName":"LIANGPING",
                "cityFirstSpell":"lp",
                "citySpell":"liangping"
            },
            {
                "airportCName":"韶关机场",
                "airportCode":"HSC",
                "cityCName":"韶关",
                "cityEName":"SHAOGUAN",
                "cityFirstSpell":"sg",
                "citySpell":"shaoguan"
            },
            {
                "airportCName":"大足机场",
                "airportCode":"DZU",
                "cityCName":"大足",
                "cityEName":"DAZU",
                "cityFirstSpell":"dz",
                "citySpell":"dazu"
            },
            {
                "airportCName":"安阳机场",
                "airportCode":"AYN",
                "cityCName":"安阳",
                "cityEName":"ANYANG",
                "cityFirstSpell":"ay",
                "citySpell":"anyang"
            },
            {
                "airportCName":"云南丽江机场",
                "airportCode":"LZJ",
                "cityCName":"丽江",
                "cityEName":"Lijiang",
                "cityFirstSpell":"lj",
                "citySpell":"lijiang"
            },
            {
                "airportCName":"阜阳西关机场",
                "airportCode":"FIG",
                "cityCName":"阜阳",
                "cityEName":"Fuyang",
                "cityFirstSpell":"fy",
                "citySpell":"fuyang"
            },
            {
                "airportCName":"遵义茅台机场",
                "airportCode":"WMT",
                "cityCName":"遵义茅台",
                "cityEName":"ZunyiMaotai",
                "cityFirstSpell":"zymt",
                "citySpell":"zunyimaotai"
            },
            {
                "airportCName":"阿尔山机场",
                "airportCode":"YIE",
                "cityCName":"阿尔山",
                "cityEName":"Aershan",
                "cityFirstSpell":"aes",
                "citySpell":"Aershan"
            },
            {
                "airportCName":"阿里昆莎机场",
                "airportCode":"NGQ",
                "cityCName":"阿里昆莎",
                "cityEName":"ALIKUNSHA",
                "cityFirstSpell":"alks",
                "citySpell":"ALIKUNSHA"
            },
            {
                "airportCName":"佤山机场",
                "airportCode":"CWJ",
                "cityCName":"沧源",
                "cityEName":"CANGYUAN",
                "cityFirstSpell":"cy",
                "citySpell":"CANGYUAN"
            },
            {
                "airportCName":"普宁机场",
                "airportCode":"CDE",
                "cityCName":"承德",
                "cityEName":"CHENGDE",
                "cityFirstSpell":"cd",
                "citySpell":"CHENGDE"
            },
            {
                "airportCName":"德令哈机场",
                "airportCode":"HXD",
                "cityCName":"德令哈",
                "cityEName":"DELINGHA",
                "cityFirstSpell":"dlh",
                "citySpell":"DELINGHA"
            },
            {
                "airportCName":"东极机场",
                "airportCode":"FYJ",
                "cityCName":"抚远",
                "cityEName":"FUYUAN",
                "cityFirstSpell":"fy",
                "citySpell":"FUYUAN"
            },
            {
                "airportCName":"玛沁机场",
                "airportCode":"GMQ",
                "cityCName":"果洛",
                "cityEName":"GUOLUO",
                "cityFirstSpell":"gl",
                "citySpell":"GUOLUO"
            },
            {
                "airportCName":"河池机场",
                "airportCode":"HCJ",
                "cityCName":"河池",
                "cityEName":"HECHI",
                "cityFirstSpell":"hc",
                "citySpell":"HECHI"
            },
            {
                "airportCName":"花土沟机场",
                "airportCode":"HTT",
                "cityCName":"花土沟",
                "cityEName":"HUATUGOU",
                "cityFirstSpell":"htg",
                "citySpell":"HUATUGOU"
            },
            {
                "airportCName":"黄石候机楼",
                "airportCode":"HSQ",
                "cityCName":"黄石",
                "cityEName":"Huangshi",
                "cityFirstSpell":"hs",
                "citySpell":"Huangshi"
            },
            {
                "airportCName":"霍林河机场",
                "airportCode":"HUO",
                "cityCName":"霍林郭勒",
                "cityEName":"HUOLINGUOLE",
                "cityFirstSpell":"hlgl",
                "citySpell":"HUOLINGUOLE"
            },
            {
                "airportCName":"加格达奇机场",
                "airportCode":"JGD",
                "cityCName":"加格达奇",
                "cityEName":"JiaGeDaQi",
                "cityFirstSpell":"jgdq",
                "citySpell":"JiaGeDaQi"
            },
            {
                "airportCName":"建三江机场",
                "airportCode":"JSJ",
                "cityCName":"建三江",
                "cityEName":"JIANSANJIANG",
                "cityFirstSpell":"jsj",
                "citySpell":"JIANSANJIANG"
            },
            {
                "airportCName":"金昌机场",
                "airportCode":"JIC",
                "cityCName":"金昌",
                "cityEName":"Jinchang",
                "cityFirstSpell":"jc",
                "citySpell":"Jinchang"
            },
            {
                "airportCName":"景迈机场",
                "airportCode":"JMJ",
                "cityCName":"澜沧",
                "cityEName":"LANCANG",
                "cityFirstSpell":"lc",
                "citySpell":"LANCANG"
            },
            {
                "airportCName":"莲花山轮渡港",
                "airportCode":"ZIY",
                "cityCName":"莲花山",
                "cityEName":"LIANHUASHAN",
                "cityFirstSpell":"lhs",
                "citySpell":"LIANHUASHAN"
            },
            {
                "airportCName":"南竿机场",
                "airportCode":"LZN",
                "cityCName":"连江",
                "cityEName":"LIANJIANG",
                "cityFirstSpell":"lj",
                "citySpell":"LIANJIANG"
            },
            {
                "airportCName":"六盘水机场",
                "airportCode":"LPF",
                "cityCName":"六盘水",
                "cityEName":"LiuPanShui",
                "cityFirstSpell":"lps",
                "citySpell":"LiuPanShui"
            },
            {
                "airportCName":"永兴机场",
                "airportCode":"XYI",
                "cityCName":"三沙",
                "cityEName":"SANSHA",
                "cityFirstSpell":"yx",
                "citySpell":"SANSHA"
            },
            {
                "airportCName":"叶尔羌机场",
                "airportCode":"QSZ",
                "cityCName":"莎车",
                "cityEName":"SHACHE",
                "cityFirstSpell":"sc",
                "citySpell":"SHACHE"
            },
            {
                "airportCName":"三清山机场",
                "airportCode":"SQD",
                "cityCName":"上饶",
                "cityEName":"Shangrao",
                "cityFirstSpell":"sr",
                "citySpell":"Shangrao"
            },
            {
                "airportCName":"武冈机场",
                "airportCode":"WGN",
                "cityCName":"邵阳",
                "cityEName":"Shaoyang",
                "cityFirstSpell":"sy",
                "citySpell":"Shaoyang"
            },
            {
                "airportCName":"松原机场",
                "airportCode":"YSQ",
                "cityCName":"松原",
                "cityEName":"Songyuan",
                "cityFirstSpell":"sy",
                "citySpell":"Songyuan"
            },
            {
                "airportCName":"乌兰察布机场",
                "airportCode":"UCB",
                "cityCName":"乌兰察布",
                "cityEName":"WULANCHABU",
                "cityFirstSpell":"wlbc",
                "citySpell":"WULANCHABU"
            },
            {
                "airportCName":"德都机场",
                "airportCode":"DTU",
                "cityCName":"五大连池",
                "cityEName":"WUDALIANCHI",
                "cityFirstSpell":"wdlc",
                "citySpell":"WUDALIANCHI"
            },
            {
                "airportCName":"夏河机场",
                "airportCode":"GXH",
                "cityCName":"夏河",
                "cityEName":"XIAHE",
                "cityFirstSpell":"xh",
                "citySpell":"XIAHE"
            },
            {
                "airportCName":"扎兰屯机场",
                "airportCode":"NZL",
                "cityCName":"扎兰屯",
                "cityEName":"ZHAKANTUN",
                "cityFirstSpell":"zlt",
                "citySpell":"ZHAKANTUN"
            },
            {
                "airportCName":"宁远机场",
                "airportCode":"ZQZ",
                "cityCName":"张家口",
                "cityEName":"ZHANGJIAKOU",
                "cityFirstSpell":"ny",
                "citySpell":"ZHANGJIAKOU"
            },
            {
                "airportCName":"临汾乔李机场",
                "airportCode":"LFQ",
                "cityCName":"临汾市",
                "cityEName":"Linfeng",
                "cityFirstSpell":"lf",
                "citySpell":"linfen"
            },
            {
                "airportCName":"巴中恩阳机场",
                "airportCode":"BZX",
                "cityCName":"巴中",
                "cityEName":"bazhong",
                "cityFirstSpell":"bz",
                "citySpell":"bazhong"
            },
            {
                "airportCName":"白城长安机场",
                "airportCode":"DBC",
                "cityCName":"白城",
                "cityEName":"BaiCheng",
                "cityFirstSpell":"bc",
                "citySpell":"baicheng"
            },
            {
                "airportCName":"荆门机场",
                "airportCode":"JM1",
                "cityCName":"荆门",
                "cityEName":"JINMEN",
                "cityFirstSpell":"jm",
                "citySpell":"jingmen"
            },
            {
                "airportCName":"呼伦贝尔",
                "airportCode":"XRQ",
                "cityCName":"呼伦贝尔",
                "cityEName":"HULUNBEIER",
                "cityFirstSpell":"hlbe",
                "citySpell":"hulunbeier"
            },
            {
                "airportCName":"陇南机场",
                "airportCode":"LNL",
                "cityCName":"陇南",
                "cityEName":"LongNan",
                "cityFirstSpell":"ln",
                "citySpell":"longnan"
            },
            {
                "airportCName":"中国马祖机场",
                "airportCode":"MFK",
                "cityCName":"马祖",
                "cityEName":"MAZHU",
                "cityFirstSpell":"mz",
                "citySpell":"mazu"
            },
            {
                "airportCName":"马公机场",
                "airportCode":"MZG",
                "cityCName":"马公",
                "cityEName":"MAGONG",
                "cityFirstSpell":"mg",
                "citySpell":"magong"
            },
            {
                "airportCName":"岳阳机场",
                "airportCode":"YYA",
                "cityCName":"岳阳",
                "cityEName":"YUEYANG",
                "cityFirstSpell":"yy",
                "citySpell":"yueyang"
            },
            {
                "airportCName":"信阳机场",
                "airportCode":"XAI",
                "cityCName":"信阳",
                "cityEName":"XINYANG",
                "cityFirstSpell":"xy",
                "citySpell":"xinyang"
            },
            {
                "airportCName":"祁连机场",
                "airportCode":"HBQ",
                "cityCName":"祁连",
                "cityEName":"QILIAN",
                "cityFirstSpell":"ql",
                "citySpell":"qilian"
            },
            {
                "airportCName":"若羌机场",
                "airportCode":"RQA",
                "cityCName":"若羌",
                "cityEName":"RuoQiang",
                "cityFirstSpell":"rq",
                "citySpell":"ruoqiang"
            },
            {
                "airportCName":"台东机场",
                "airportCode":"TTT",
                "cityCName":"台东",
                "cityEName":"TAIDONG",
                "cityFirstSpell":"td",
                "citySpell":"taidong"
            },
            {
                "airportCName":"乌拉特中旗机场",
                "airportCode":"WZQ",
                "cityCName":"乌拉特中旗",
                "cityEName":"wulatezhongqi",
                "cityFirstSpell":"wltzq",
                "citySpell":"wulatezhongqi"
            },
            {
                "airportCName":"巫山机场",
                "airportCode":"WSK",
                "cityCName":"巫山",
                "cityEName":"Wushang",
                "cityFirstSpell":"ws",
                "citySpell":"wushan"
            }
        ],
        "addressAirportHot":[			          
            {
                "airportCName":"北京大兴国际机场",
                "airportCode":"PKX",
                "cityCName":"北京大兴",
                "cityEName":"Beijing",
                "cityFirstSpell":"bj",
                "citySpell":"beijing"
            },
			{
			    "airportCName":"北京首都国际机场",
			    "airportCode":"PEK",
			    "cityCName":"北京首都",
			    "cityEName":"beijing",
			    "cityFirstSpell":"bj",
			    "citySpell":"beijing"
			},
			{
			    "airportCName":"上海浦东机场",
			    "airportCode":"PVG",
			    "cityCName":"上海浦东",
			    "cityEName":"Shanghai",
			    "cityFirstSpell":"sh",
			    "citySpell":"shanghai"
			},
			{
			    "airportCName":"上海虹桥机场",
			    "airportCode":"SHA",
			    "cityCName":"上海虹桥",
			    "cityEName":"Shanghai",
			    "cityFirstSpell":"sh",
			    "citySpell":"shanghai"
			},
			{
			    "airportCName":"广州白云机场",
			    "airportCode":"CAN",
			    "cityCName":"广州",
			    "cityEName":"Guangzhou",
			    "cityFirstSpell":"gz",
			    "citySpell":"guangzhou"
			},
			{
			    "airportCName":"深圳宝安国际机场",
			    "airportCode":"SZX",
			    "cityCName":"深圳",
			    "cityEName":"Shenzhen",
			    "cityFirstSpell":"sz",
			    "citySpell":"shenzhen"
			},
			{
			    "airportCName":"惠州机场",
			    "airportCode":"HUZ",
			    "cityCName":"惠州",
			    "cityEName":"Huizhou",
			    "cityFirstSpell":"hz",
			    "citySpell":"huizhou"
			},			
            {
                "airportCName":"武汉天河机场",
                "airportCode":"WUH",
                "cityCName":"武汉",
                "cityEName":"Wuhan",
                "cityFirstSpell":"wh",
                "citySpell":"wuhan"
            },
			{
			    "airportCName":"成都双流国际机场",
			    "airportCode":"CTU",
			    "cityCName":"成都",
			    "cityEName":"Chengdu",
			    "cityFirstSpell":"cd",
			    "citySpell":"chengdou"
			},
            {
                "airportCName":"长沙黄花机场",
                "airportCode":"CSX",
                "cityCName":"长沙",
                "cityEName":"Changsha",
                "cityFirstSpell":"cs",
                "citySpell":"Changsha"
            },
            {
                "airportCName":"郑州新郑机场",
                "airportCode":"CGO",
                "cityCName":"郑州",
                "cityEName":"Zhengzhou",
                "cityFirstSpell":"zz",
                "citySpell":"zhengzhou"
            },
            {
                "airportCName":"南京禄口机场",
                "airportCode":"NKG",
                "cityCName":"南京",
                "cityEName":"Nanjing",
                "cityFirstSpell":"nj",
                "citySpell":"nanjing"
            },
            {
                "airportCName":"大连周水子国际机场",
                "airportCode":"DLC",
                "cityCName":"大连",
                "cityEName":"Dalian",
                "cityFirstSpell":"dl",
                "citySpell":"dalian"
            },
            {
                "airportCName":"济南机场",
                "airportCode":"TNA",
                "cityCName":"济南",
                "cityEName":"Jinan",
                "cityFirstSpell":"jn",
                "citySpell":"jinan"
            },
           
			{
			    "airportCName":"海口美兰机场",
			    "airportCode":"HAK",
			    "cityCName":"海口",
			    "cityEName":"Haikou",
			    "cityFirstSpell":"hk",
			    "citySpell":"haikou"
			},
            {
                "airportCName":"青岛流亭机场",
                "airportCode":"TAO",
                "cityCName":"青岛",
                "cityEName":"Qingdao",
                "cityFirstSpell":"qd",
                "citySpell":"qingdao"
            },           
           
            {
                "airportCName":"滨海国际机场",
                "airportCode":"TSN",
                "cityCName":"天津",
                "cityEName":"Tianjin",
                "cityFirstSpell":"tj",
                "citySpell":"tianjin"
            },
           
            {
                "airportCName":"三亚凤凰机场",
                "airportCode":"SYX",
                "cityCName":"三亚",
                "cityEName":"Sanya",
                "cityFirstSpell":"sy",
                "citySpell":"sanya"
            },
           
            {
                "airportCName":"昆明长水国际机场",
                "airportCode":"KMG",
                "cityCName":"昆明",
                "cityEName":"Kunming",
                "cityFirstSpell":"km",
                "citySpell":"kunming"
            },
            {
                "airportCName":"杭州萧山国际机场",
                "airportCode":"HGH",
                "cityCName":"杭州",
                "cityEName":"Hangzhou",
                "cityFirstSpell":"hz",
                "citySpell":"hangzhou"
            },
            {
                "airportCName":"重庆江北国际机场",
                "airportCode":"CKG",
                "cityCName":"重庆",
                "cityEName":"Chongqing",
                "cityFirstSpell":"zq",
                "citySpell":"zhongqing"
            },
            {
                "airportCName":"福州长乐机场",
                "airportCode":"FOC",
                "cityCName":"福州",
                "cityEName":"Fuzhou",
                "cityFirstSpell":"fz",
                "citySpell":"fuzhou"
            },
            {
                "airportCName":"厦门高崎机场",
                "airportCode":"XMN",
                "cityCName":"厦门",
                "cityEName":"Xiamen",
                "cityFirstSpell":"sm",
                "citySpell":"shamen"
            }
        ]
}
export default airports