export default{
    "addressAirportAll":[
        {
            "airportCode":"WUZ",
            "cityCName":"梧州",
            "cityEName":"Wuzhou",
            "cityFirstSpell":"wz",
            "citySpell":"wuzhou"
        },
        {
            "airportCode":"AVA",
            "cityCName":"安顺",
            "cityEName":"Anshun",
            "cityFirstSpell":"as",
            "citySpell":"anshun"
        },
        {
            "airportCode":"KWE",
            "cityCName":"贵阳",
            "cityEName":"Guiyang",
            "cityFirstSpell":"gy",
            "citySpell":"guiyang"
        },
        {
            "airportCode":"TEN",
            "cityCName":"铜仁",
            "cityEName":"Tongren",
            "cityFirstSpell":"tr",
            "citySpell":"tongren"
        },
        {
            "airportCode":"ZYI",
            "cityCName":"遵义新舟",
            "cityEName":"ZunyiXinzhou",
            "cityFirstSpell":"zyxz",
            "citySpell":"zunyixinzhou"
        },
        {
            "airportCode":"HAK",
            "cityCName":"海口",
            "cityEName":"Haikou",
            "cityFirstSpell":"hk",
            "citySpell":"haikou"
        },
        {
            "airportCode":"HDG",
            "cityCName":"邯郸",
            "cityEName":"Handan",
            "cityFirstSpell":"hd",
            "citySpell":"handan"
        },
        {
            "airportCode":"HHA",
            "cityCName":"黄骅",
            "cityEName":"Huangye",
            "cityFirstSpell":"hh",
            "citySpell":"huanghua"
        },
        {
            "airportCode":"SJW",
            "cityCName":"石家庄",
            "cityEName":"Shijiazhuang",
            "cityFirstSpell":"sjz",
            "citySpell":"shijiazhuang"
        },
        {
            "airportCode":"LYA",
            "cityCName":"洛阳",
            "cityEName":"LuoYang",
            "cityFirstSpell":"ly",
            "citySpell":"luoyang"
        },
        {
            "airportCode":"HRB",
            "cityCName":"哈尔滨",
            "cityEName":"Harbin",
            "cityFirstSpell":"heb",
            "citySpell":"haerbin"
        },
        {
            "airportCode":"JMU",
            "cityCName":"佳木斯",
            "cityEName":"Jiamusi",
            "cityFirstSpell":"jms",
            "citySpell":"jiamusi"
        },
        {
            "airportCode":"MDG",
            "cityCName":"牡丹江",
            "cityEName":"Mudanjiang",
            "cityFirstSpell":"mdj",
            "citySpell":"mudanjiang"
        },
        {
            "airportCode":"ENH",
            "cityCName":"恩施",
            "cityEName":"Enshi",
            "cityFirstSpell":"es",
            "citySpell":"enshi"
        },
        {
            "airportCode":"NLT",
            "cityCName":"那拉提",
            "cityEName":"NALATI",
            "cityFirstSpell":"nlt",
            "citySpell":"nalati"
        },
        {
            "airportCode":"DSN",
            "cityCName":"鄂尔多斯",
            "cityEName":"Eerduosi",
            "cityFirstSpell":"eeds",
            "citySpell":"eerduosi"
        },
        {
            "airportCode":"LLF",
            "cityCName":"永州",
            "cityEName":"Yongzhou",
            "cityFirstSpell":"yz",
            "citySpell":"yongzhou"
        },
        {
            "airportCode":"KCA",
            "cityCName":"库车",
            "cityEName":"Kuqa",
            "cityFirstSpell":"kc",
            "citySpell":"kuche"
        },
        {
            "airportCode":"LCX",
            "cityCName":"连城",
            "cityEName":"Liancheng",
            "cityFirstSpell":"lc",
            "citySpell":"liancheng"
        },
        {
            "airportCode":"LUM",
            "cityCName":"芒市",
            "cityEName":"Mangshi",
            "cityFirstSpell":"ms",
            "citySpell":"mangshi"
        },
        {
            "airportCode":"WXN",
            "cityCName":"万州",
            "cityEName":"Wanxian",
            "cityFirstSpell":"wz",
            "citySpell":"wanzhou"
        },
        {
            "airportCode":"CNI",
            "cityCName":"长海",
            "cityEName":"Changhai",
            "cityFirstSpell":"zh",
            "citySpell":"changhai"
        },
        {
            "airportCode":"HJJ",
            "cityCName":"芷江",
            "cityEName":"Zhijiang",
            "cityFirstSpell":"zj",
            "citySpell":"zhijiang"
        },
        {
            "airportCode":"NAY",
            "cityCName":"北京大兴国际",
            "cityEName":"Beijingnanyuan",
            "cityFirstSpell":"bj",
            "citySpell":"beijing"
        },
        {
            "airportCode":"AQG",
            "cityCName":"安庆",
            "cityEName":"Anqing",
            "cityFirstSpell":"aq",
            "citySpell":"anqing"
        },
        {
            "airportCode":"BFU",
            "cityCName":"蚌埠",
            "cityEName":"Bengbu",
            "cityFirstSpell":"bb",
            "citySpell":"bangbu"
        },
        {
            "airportCode":"SHS",
            "cityCName":"荆州",
            "cityEName":"Jingzhou",
            "cityFirstSpell":"jz",
            "citySpell":"jingzhou"
        },
        {
            "airportCode":"WUH",
            "cityCName":"武汉",
            "cityEName":"Wuhan",
            "cityFirstSpell":"wh",
            "citySpell":"wuhan"
        },
        {
            "airportCode":"YIH",
            "cityCName":"宜昌",
            "cityEName":"Yichang",
            "cityFirstSpell":"yc",
            "citySpell":"yichang"
        },
        {
            "airportCode":"CGD",
            "cityCName":"常德",
            "cityEName":"Changde",
            "cityFirstSpell":"cd",
            "citySpell":"changde"
        },
        {
            "airportCode":"CSX",
            "cityCName":"长沙",
            "cityEName":"Changsha",
            "cityFirstSpell":"cs",
            "citySpell":"Changsha"
        },
        {
            "airportCode":"LZY",
            "cityCName":"林芝",
            "cityEName":"Linzhi",
            "cityFirstSpell":"lz",
            "citySpell":"linzhi"
        },
        {
            "airportCode":"INC",
            "cityCName":"银川",
            "cityEName":"Yinchuan",
            "cityFirstSpell":"yc",
            "citySpell":"yinchuan"
        },
        {
            "airportCode":"GOQ",
            "cityCName":"格尔木",
            "cityEName":"Golmud",
            "cityFirstSpell":"gem",
            "citySpell":"geermu"
        },
        {
            "airportCode":"XNN",
            "cityCName":"西宁",
            "cityEName":"Xining",
            "cityFirstSpell":"xn",
            "citySpell":"xining"
        },
        {
            "airportCode":"AKU",
            "cityCName":"阿克苏",
            "cityEName":"Aksu",
            "cityFirstSpell":"aks",
            "citySpell":"akesu"
        },
        {
            "airportCode":"AAT",
            "cityCName":"阿勒泰",
            "cityEName":"Altay",
            "cityFirstSpell":"alt",
            "citySpell":"aletai"
        },
        {
            "airportCode":"CGO",
            "cityCName":"郑州",
            "cityEName":"Zhengzhou",
            "cityFirstSpell":"zz",
            "citySpell":"zhengzhou"
        },
        {
            "airportCode":"KOW",
            "cityCName":"赣州",
            "cityEName":"Ganzhou",
            "cityFirstSpell":"gz",
            "citySpell":"ganzhou"
        },
        {
            "airportCode":"WUS",
            "cityCName":"武夷山",
            "cityEName":"Wuyishan",
            "cityFirstSpell":"wys",
            "citySpell":"wuyishan"
        },
        {
            "airportCode":"DNH",
            "cityCName":"敦煌",
            "cityEName":"Dunhuang",
            "cityFirstSpell":"dh",
            "citySpell":"dunhuang"
        },
        {
            "airportCode":"KNC",
            "cityCName":"吉安",
            "cityEName":"Ji'an",
            "cityFirstSpell":"ja",
            "citySpell":"jian"
        },
        {
            "airportCode":"NBS",
            "cityCName":"长白山",
            "cityEName":"Baishan",
            "cityFirstSpell":"zbs",
            "citySpell":"changbaishan"
        },
        {
            "airportCode":"CGQ",
            "cityCName":"长春",
            "cityEName":"Changchun",
            "cityFirstSpell":"zc",
            "citySpell":"changchun"
        },
        {
            "airportCode":"JIL",
            "cityCName":"吉林",
            "cityEName":"Jilin",
            "cityFirstSpell":"jl",
            "citySpell":"jilin"
        },
        {
            "airportCode":"TNH",
            "cityCName":"通化",
            "cityEName":"Tonghua",
            "cityFirstSpell":"th",
            "citySpell":"tonghua"
        },
        {
            "airportCode":"YNJ",
            "cityCName":"延吉",
            "cityEName":"Yanji",
            "cityFirstSpell":"yj",
            "citySpell":"yanji"
        },
        {
            "airportCode":"CZX",
            "cityCName":"常州",
            "cityEName":"Changzhou",
            "cityFirstSpell":"cz",
            "citySpell":"changzhou"
        },
        {
            "airportCode":"HIA",
            "cityCName":"淮安",
            "cityEName":"Huaian",
            "cityFirstSpell":"ha",
            "citySpell":"huaian"
        },
        {
            "airportCode":"LYG",
            "cityCName":"连云港",
            "cityEName":"Liangyungang",
            "cityFirstSpell":"lyg",
            "citySpell":"lianyungang"
        },
        {
            "airportCode":"NKG",
            "cityCName":"南京",
            "cityEName":"Nanjing",
            "cityFirstSpell":"nj",
            "citySpell":"nanjing"
        },
        {
            "airportCode":"NTG",
            "cityCName":"南通",
            "cityEName":"Nantong",
            "cityFirstSpell":"nt",
            "citySpell":"nantong"
        },
        {
            "airportCode":"SZV",
            "cityCName":"苏州",
            "cityEName":"Suzhou",
            "cityFirstSpell":"sz",
            "citySpell":"suzhou"
        },
        {
            "airportCode":"WUX",
            "cityCName":"无锡",
            "cityEName":"Wuxi",
            "cityFirstSpell":"wx",
            "citySpell":"wuxi"
        },
        {
            "airportCode":"XUZ",
            "cityCName":"徐州",
            "cityEName":"Xuzhou",
            "cityFirstSpell":"xz",
            "citySpell":"xuzhou"
        },
        {
            "airportCode":"YNZ",
            "cityCName":"盐城",
            "cityEName":"Yancheng",
            "cityFirstSpell":"yc",
            "citySpell":"yancheng"
        },
        {
            "airportCode":"JGS",
            "cityCName":"井冈山",
            "cityEName":"Jinggangshan",
            "cityFirstSpell":"jgs",
            "citySpell":"jinggangshan"
        },
        {
            "airportCode":"JDZ",
            "cityCName":"景德镇",
            "cityEName":"Jingdezhen",
            "cityFirstSpell":"jdz",
            "citySpell":"jingdezhen"
        },
        {
            "airportCode":"JIU",
            "cityCName":"九江",
            "cityEName":"Jiujiang",
            "cityFirstSpell":"jj",
            "citySpell":"jiujiang"
        },
        {
            "airportCode":"KHN",
            "cityCName":"南昌",
            "cityEName":"Nanchang",
            "cityFirstSpell":"nc",
            "citySpell":"nanchang"
        },
        {
            "airportCode":"AOG",
            "cityCName":"鞍山",
            "cityEName":"Anshan",
            "cityFirstSpell":"as",
            "citySpell":"anshan"
        },
        {
            "airportCode":"DDG",
            "cityCName":"丹东",
            "cityEName":"Dandong",
            "cityFirstSpell":"dd",
            "citySpell":"dandong"
        },
        {
            "airportCode":"DLC",
            "cityCName":"大连",
            "cityEName":"Dalian",
            "cityFirstSpell":"dl",
            "citySpell":"dalian"
        },
        {
            "airportCode":"HLD",
            "cityCName":"海拉尔",
            "cityEName":"Huludao",
            "cityFirstSpell":"hle",
            "citySpell":"hailaer"
        },
        {
            "airportCode":"JNZ",
            "cityCName":"锦州",
            "cityEName":"Jinzhou",
            "cityFirstSpell":"jz",
            "citySpell":"jinzhou"
        },
        {
            "airportCode":"SHE",
            "cityCName":"沈阳",
            "cityEName":"Shenyang",
            "cityFirstSpell":"sy",
            "citySpell":"shenyang"
        },
        {
            "airportCode":"XEN",
            "cityCName":"兴城",
            "cityEName":"Xingcheng",
            "cityFirstSpell":"xc",
            "citySpell":"xingcheng"
        },
        {
            "airportCode":"DOY",
            "cityCName":"东营",
            "cityEName":"Dongying",
            "cityFirstSpell":"dy",
            "citySpell":"dongying"
        },
        {
            "airportCode":"TNA",
            "cityCName":"济南",
            "cityEName":"Jinan",
            "cityFirstSpell":"jn",
            "citySpell":"jinan"
        },
        {
            "airportCode":"JNG",
            "cityCName":"济宁",
            "cityEName":"Jining",
            "cityFirstSpell":"jn",
            "citySpell":"jining"
        },
        {
            "airportCode":"LYI",
            "cityCName":"临沂",
            "cityEName":"Linyi",
            "cityFirstSpell":"ly",
            "citySpell":"linyi"
        },
        {
            "airportCode":"PEK",
            "cityCName":"北京首都",
            "cityEName":"beijing",
            "cityFirstSpell":"bj",
            "citySpell":"beijing"
        },
        {
            "airportCode":"TAO",
            "cityCName":"青岛",
            "cityEName":"Qingdao",
            "cityFirstSpell":"qd",
            "citySpell":"qingdao"
        },
        {
            "airportCode":"CHW",
            "cityCName":"酒泉",
            "cityEName":"Jiuquan",
            "cityFirstSpell":"jq",
            "citySpell":"jiuquan"
        },
        {
            "airportCode":"JGN",
            "cityCName":"嘉峪关",
            "cityEName":"Jiayuguan",
            "cityFirstSpell":"jyg",
            "citySpell":"jiayuguan"
        },
        {
            "airportCode":"LHW",
            "cityCName":"兰州",
            "cityEName":"Lanzhou",
            "cityFirstSpell":"lz",
            "citySpell":"lanzhou"
        },
        {
            "airportCode":"IQN",
            "cityCName":"庆阳",
            "cityEName":"Qingyang",
            "cityFirstSpell":"qy",
            "citySpell":"qingyang"
        },
        {
            "airportCode":"PNJ",
            "cityCName":"蓬莱",
            "cityEName":"Penglai",
            "cityFirstSpell":"pl",
            "citySpell":"penglai"
        },
        {
            "airportCode":"WEH",
            "cityCName":"威海",
            "cityEName":"Wendeng",
            "cityFirstSpell":"wh",
            "citySpell":"weihai"
        },
        {
            "airportCode":"WEF",
            "cityCName":"潍坊",
            "cityEName":"Weifang",
            "cityFirstSpell":"wf",
            "citySpell":"weifang"
        },
        {
            "airportCode":"YNT",
            "cityCName":"烟台",
            "cityEName":"Yantai",
            "cityFirstSpell":"yt",
            "citySpell":"yantai"
        },
        {
            "airportCode":"CIH",
            "cityCName":"长治",
            "cityEName":"Changzhi",
            "cityFirstSpell":"zz",
            "citySpell":"changzhi"
        },
        {
            "airportCode":"DAT",
            "cityCName":"大同",
            "cityEName":"Datong",
            "cityFirstSpell":"dt",
            "citySpell":"datong"
        },
        {
            "airportCode":"TYN",
            "cityCName":"太原",
            "cityEName":"Taiyuan",
            "cityFirstSpell":"ty",
            "citySpell":"taiyuan"
        },
        {
            "airportCode":"WUT",
            "cityCName":"五台山",
            "cityEName":"Wutaishan",
            "cityFirstSpell":"wts",
            "citySpell":"wutaishan"
        },
        {
            "airportCode":"YCU",
            "cityCName":"运城",
            "cityEName":"Yuncheng",
            "cityFirstSpell":"yc",
            "citySpell":"yuncheng"
        },
        {
            "airportCode":"AKA",
            "cityCName":"安康",
            "cityEName":"Ankang",
            "cityFirstSpell":"ak",
            "citySpell":"ankang"
        },
        {
            "airportCode":"XIY",
            "cityCName":"西安/咸阳",
            "cityEName":"Xi'an",
            "cityFirstSpell":"xa/xy",
            "citySpell":"xi'an"
        },
        {
            "airportCode":"ENY",
            "cityCName":"延安",
            "cityEName":"Yanan",
            "cityFirstSpell":"ya",
            "citySpell":"yanan"
        },
        {
            "airportCode":"UYN",
            "cityCName":"榆林",
            "cityEName":"Yulin",
            "cityFirstSpell":"yl",
            "citySpell":"yulin"
        },
        {
            "airportCode":"PVG",
            "cityCName":"上海浦东",
            "cityEName":"Shanghai",
            "cityFirstSpell":"sh",
            "citySpell":"shanghai"
        },
        {
            "airportCode":"CTU",
            "cityCName":"成都",
            "cityEName":"Chengdu",
            "cityFirstSpell":"cd",
            "citySpell":"chengdou"
        },
        {
            "airportCode":"DAX",
            "cityCName":"达县",
            "cityEName":"Dazhou",
            "cityFirstSpell":"dx",
            "citySpell":"daxian"
        },
        {
            "airportCode":"GHN",
            "cityCName":"广汉",
            "cityEName":"Guanghan",
            "cityFirstSpell":"gh",
            "citySpell":"guanghan"
        },
        {
            "airportCode":"GYS",
            "cityCName":"广元",
            "cityEName":"Guangyuan",
            "cityFirstSpell":"gy",
            "citySpell":"guangyuan"
        },
        {
            "airportCode":"JZH",
            "cityCName":"九寨沟",
            "cityEName":"Jiuzhaigou",
            "cityFirstSpell":"jzg",
            "citySpell":"jiuzhaigou"
        },
        {
            "airportCode":"LZO",
            "cityCName":"泸州",
            "cityEName":"Luzhou",
            "cityFirstSpell":"lz",
            "citySpell":"luzhou"
        },
        {
            "airportCode":"MIG",
            "cityCName":"绵阳",
            "cityEName":"Mianyang",
            "cityFirstSpell":"my",
            "citySpell":"mianyang"
        },
        {
            "airportCode":"NAO",
            "cityCName":"南充",
            "cityEName":"Nanchong",
            "cityFirstSpell":"nc",
            "citySpell":"nanchong"
        },
        {
            "airportCode":"PZI",
            "cityCName":"攀枝花",
            "cityEName":"Panzhihua",
            "cityFirstSpell":"pzh",
            "citySpell":"panzhihua"
        },
        {
            "airportCode":"XIC",
            "cityCName":"西昌",
            "cityEName":"Xichang",
            "cityFirstSpell":"xc",
            "citySpell":"xichang"
        },
        {
            "airportCode":"YBP",
            "cityCName":"宜宾",
            "cityEName":"Yibin",
            "cityFirstSpell":"yb",
            "citySpell":"yibin"
        },
        {
            "airportCode":"TSN",
            "cityCName":"天津",
            "cityEName":"Tianjin",
            "cityFirstSpell":"tj",
            "citySpell":"tianjin"
        },
        {
            "airportCode":"BPX",
            "cityCName":"昌都",
            "cityEName":"Changdu",
            "cityFirstSpell":"cd",
            "citySpell":"changdou"
        },
        {
            "airportCode":"SHA",
            "cityCName":"上海虹桥",
            "cityEName":"Shanghai",
            "cityFirstSpell":"sh",
            "citySpell":"shanghai"
        },
        {
            "airportCode":"IQM",
            "cityCName":"且末",
            "cityEName":"Qiemo",
            "cityFirstSpell":"qm",
            "citySpell":"qiemo"
        },
        {
            "airportCode":"NDG",
            "cityCName":"齐齐哈尔",
            "cityEName":"QiqIihar",
            "cityFirstSpell":"qqhe",
            "citySpell":"qiqihaer"
        },
        {
            "airportCode":"SYX",
            "cityCName":"三亚",
            "cityEName":"Sanya",
            "cityFirstSpell":"sy",
            "citySpell":"sanya"
        },
        {
            "airportCode":"HFE",
            "cityCName":"合肥",
            "cityEName":"Hefei",
            "cityFirstSpell":"hf",
            "citySpell":"hefei"
        },
        {
            "airportCode":"FUG",
            "cityCName":"阜阳",
            "cityEName":"Fuyang",
            "cityFirstSpell":"fy",
            "citySpell":"fuyang"
        },
        {
            "airportCode":"TXN",
            "cityCName":"黄山",
            "cityEName":"Huangshan",
            "cityFirstSpell":"hs",
            "citySpell":"huangshan"
        },
        {
            "airportCode":"WHU",
            "cityCName":"芜湖",
            "cityEName":"Wuhu",
            "cityFirstSpell":"wh",
            "citySpell":"wuhu"
        },
        {
            "airportCode":"FUO",
            "cityCName":"佛山",
            "cityEName":"Fuoshan",
            "cityFirstSpell":"fs",
            "citySpell":"foshan"
        },
        {
            "airportCode":"CAN",
            "cityCName":"广州",
            "cityEName":"Guangzhou",
            "cityFirstSpell":"gz",
            "citySpell":"guangzhou"
        },
        {
            "airportCode":"HUZ",
            "cityCName":"惠州",
            "cityEName":"Huizhou",
            "cityFirstSpell":"hz",
            "citySpell":"huizhou"
        },
        {
            "airportCode":"SWA",
            "cityCName":"揭阳",
            "cityEName":"JIEYANG",
            "cityFirstSpell":"jy",
            "citySpell":"jieyang"
        },
        {
            "airportCode":"SZX",
            "cityCName":"深圳",
            "cityEName":"Shenzhen",
            "cityFirstSpell":"sz",
            "citySpell":"shenzhen"
        },
        {
            "airportCode":"ZUH",
            "cityCName":"珠海",
            "cityEName":"Zhuhai",
            "cityFirstSpell":"zh",
            "citySpell":"zhuhai"
        },
        {
            "airportCode":"ZHA",
            "cityCName":"湛江",
            "cityEName":"Zhanjiang",
            "cityFirstSpell":"zj",
            "citySpell":"zhanjiang"
        },
        {
            "airportCode":"BHY",
            "cityCName":"北海",
            "cityEName":"Beihai",
            "cityFirstSpell":"bh",
            "citySpell":"beihai"
        },
        {
            "airportCode":"AEB",
            "cityCName":"百色",
            "cityEName":"BOSE",
            "cityFirstSpell":"bs",
            "citySpell":"baise"
        },
        {
            "airportCode":"KWL",
            "cityCName":"桂林",
            "cityEName":"Guilin",
            "cityFirstSpell":"gl",
            "citySpell":"guilin"
        },
        {
            "airportCode":"HZH",
            "cityCName":"黎平",
            "cityEName":"Hezhou",
            "cityFirstSpell":"lp",
            "citySpell":"liping"
        },
        {
            "airportCode":"LZH",
            "cityCName":"柳州",
            "cityEName":"Liuzhou",
            "cityFirstSpell":"lz",
            "citySpell":"liuzhou"
        },
        {
            "airportCode":"NNG",
            "cityCName":"南宁",
            "cityEName":"Nanning",
            "cityFirstSpell":"nn",
            "citySpell":"nanning"
        },
        {
            "airportCode":"TCG",
            "cityCName":"塔城",
            "cityEName":"Tacheng",
            "cityFirstSpell":"tc",
            "citySpell":"tacheng"
        },
        {
            "airportCode":"URC",
            "cityCName":"乌鲁木齐",
            "cityEName":"WUrumqi",
            "cityFirstSpell":"wlmq",
            "citySpell":"wulumuqi"
        },
        {
            "airportCode":"YIN",
            "cityCName":"伊宁",
            "cityEName":"Yining",
            "cityFirstSpell":"yn",
            "citySpell":"yining"
        },
        {
            "airportCode":"BSD",
            "cityCName":"保山",
            "cityEName":"Baoshan",
            "cityFirstSpell":"bs",
            "citySpell":"baoshan"
        },
        {
            "airportCode":"DLU",
            "cityCName":"大理",
            "cityEName":"Dali",
            "cityFirstSpell":"dl",
            "citySpell":"dali"
        },
        {
            "airportCode":"DIG",
            "cityCName":"迪庆",
            "cityEName":"Diqing",
            "cityFirstSpell":"dq",
            "citySpell":"diqing"
        },
        {
            "airportCode":"KMG",
            "cityCName":"昆明",
            "cityEName":"Kunming",
            "cityFirstSpell":"km",
            "citySpell":"kunming"
        },
        {
            "airportCode":"LNJ",
            "cityCName":"临沧",
            "cityEName":"Lincang",
            "cityFirstSpell":"lc",
            "citySpell":"lincang"
        },
        {
            "airportCode":"LJG",
            "cityCName":"丽江",
            "cityEName":"Lijiang",
            "cityFirstSpell":"lj",
            "citySpell":"lijiang"
        },
        {
            "airportCode":"SYM",
            "cityCName":"思茅",
            "cityEName":"Simao",
            "cityFirstSpell":"sm",
            "citySpell":"simao"
        },
        {
            "airportCode":"JHG",
            "cityCName":"西双版纳",
            "cityEName":"XSBN",
            "cityFirstSpell":"xsbn",
            "citySpell":"xishuangbanna"
        },
        {
            "airportCode":"ZAT",
            "cityCName":"昭通",
            "cityEName":"Zhaotong",
            "cityFirstSpell":"zt",
            "citySpell":"zhaotong"
        },
        {
            "airportCode":"HYN",
            "cityCName":"台州",
            "cityEName":"TAIZHOU",
            "cityFirstSpell":"tz",
            "citySpell":"taizhou"
        },
        {
            "airportCode":"HGH",
            "cityCName":"杭州",
            "cityEName":"Hangzhou",
            "cityFirstSpell":"hz",
            "citySpell":"hangzhou"
        },
        {
            "airportCode":"NGB",
            "cityCName":"宁波",
            "cityEName":"Ningbo",
            "cityFirstSpell":"nb",
            "citySpell":"ningbo"
        },
        {
            "airportCode":"JUZ",
            "cityCName":"衢州",
            "cityEName":"Quzhou",
            "cityFirstSpell":"qz",
            "citySpell":"quzhou"
        },
        {
            "airportCode":"WNZ",
            "cityCName":"温州",
            "cityEName":"Wenzhou",
            "cityFirstSpell":"wz",
            "citySpell":"wenzhou"
        },
        {
            "airportCode":"YIW",
            "cityCName":"义乌",
            "cityEName":"Yiwu",
            "cityFirstSpell":"yw",
            "citySpell":"yiwu"
        },
        {
            "airportCode":"CKG",
            "cityCName":"重庆",
            "cityEName":"Chongqing",
            "cityFirstSpell":"zq",
            "citySpell":"zhongqing"
        },
        {
            "airportCode":"FOC",
            "cityCName":"福州",
            "cityEName":"Fuzhou",
            "cityFirstSpell":"fz",
            "citySpell":"fuzhou"
        },
        {
            "airportCode":"JJN",
            "cityCName":"泉州晋江",
            "cityEName":"Quanzhou",
            "cityFirstSpell":"qzjj",
            "citySpell":"quanzhoujinjiang"
        },
        {
            "airportCode":"XMN",
            "cityCName":"厦门",
            "cityEName":"Xiamen",
            "cityFirstSpell":"sm",
            "citySpell":"shamen"
        },
        {
            "airportCode":"BAV",
            "cityCName":"包头",
            "cityEName":"Baotou",
            "cityFirstSpell":"bt",
            "citySpell":"baotou"
        },
        {
            "airportCode":"CIF",
            "cityCName":"赤峰",
            "cityEName":"Chifeng",
            "cityFirstSpell":"cf",
            "citySpell":"chifeng"
        },
        {
            "airportCode":"NZH",
            "cityCName":"满洲里",
            "cityEName":"Manzhouli",
            "cityFirstSpell":"mzl",
            "citySpell":"manzhouli"
        },
        {
            "airportCode":"TGO",
            "cityCName":"通辽",
            "cityEName":"Tongliao",
            "cityFirstSpell":"tl",
            "citySpell":"tongliao"
        },
        {
            "airportCode":"WUA",
            "cityCName":"乌海",
            "cityEName":"Wuhai",
            "cityFirstSpell":"wh",
            "citySpell":"wuhai"
        },
        {
            "airportCode":"HLH",
            "cityCName":"乌兰浩特",
            "cityEName":"WUlanhot",
            "cityFirstSpell":"wlht",
            "citySpell":"wulanhaote"
        },
        {
            "airportCode":"XIL",
            "cityCName":"锡林浩特",
            "cityEName":"Xilinhot",
            "cityFirstSpell":"xlht",
            "citySpell":"xilinhaote"
        },
        {
            "airportCode":"LXA",
            "cityCName":"拉萨",
            "cityEName":"LaSa",
            "cityFirstSpell":"ls",
            "citySpell":"lasa"
        },
        {
            "airportCode":"HNY",
            "cityCName":"衡阳",
            "cityEName":"Hengyang",
            "cityFirstSpell":"hy",
            "citySpell":"hengyang"
        },
        {
            "airportCode":"HSN",
            "cityCName":"舟山",
            "cityEName":"Zhoushan",
            "cityFirstSpell":"zs",
            "citySpell":"zhoushan"
        },
        {
            "airportCode":"HZG",
            "cityCName":"汉中",
            "cityEName":"Hanzhong",
            "cityFirstSpell":"hz",
            "citySpell":"hanzhong"
        },
        {
            "airportCode":"MXZ",
            "cityCName":"梅县",
            "cityEName":"Meixian",
            "cityFirstSpell":"mx",
            "citySpell":"meixian"
        },
        {
            "airportCode":"DYG",
            "cityCName":"张家界",
            "cityEName":"Zhangjiajie",
            "cityFirstSpell":"zjj",
            "citySpell":"zhangjiajie"
        },
        {
            "airportCode":"FYN",
            "cityCName":"富蕴",
            "cityEName":"FuYun",
            "cityFirstSpell":"fy",
            "citySpell":"fuyun"
        },
        {
            "airportCode":"XFN",
            "cityCName":"襄樊",
            "cityEName":"Xiangfan",
            "cityFirstSpell":"xf",
            "citySpell":"xiangfan"
        },
        {
            "airportCode":"HET",
            "cityCName":"呼和浩特",
            "cityEName":"HoHeHaoTe",
            "cityFirstSpell":"hhht",
            "citySpell":"huhehaote"
        },
        {
            "airportCode":"HTN",
            "cityCName":"和田",
            "cityEName":"Hotan",
            "cityFirstSpell":"ht",
            "citySpell":"hetian"
        },
        {
            "airportCode":"KRL",
            "cityCName":"库尔勒",
            "cityEName":"Korla",
            "cityFirstSpell":"kel",
            "citySpell":"kuerle"
        },
        {
            "airportCode":"KRY",
            "cityCName":"克拉玛依",
            "cityEName":"Kalamayi",
            "cityFirstSpell":"klmy",
            "citySpell":"kelamayi"
        },
        {
            "airportCode":"KHG",
            "cityCName":"喀什",
            "cityEName":"Kashi",
            "cityFirstSpell":"ks",
            "citySpell":"kashen"
        },
        {
            "airportCode":"TVS",
            "cityCName":"唐山",
            "cityEName":"Tangshan",
            "cityFirstSpell":"ts",
            "citySpell":"tangshan"
        },
        {
            "airportCode":"BFJ",
            "cityCName":"毕节",
            "cityEName":"BIJIE",
            "cityFirstSpell":"bj",
            "citySpell":"bijie"
        },
        {
            "airportCode":"HEK",
            "cityCName":"黑河",
            "cityEName":"Heihe",
            "cityFirstSpell":"hh",
            "citySpell":"heihe"
        },
        {
            "airportCode":"THQ",
            "cityCName":"天水",
            "cityEName":"Tianshui",
            "cityFirstSpell":"ts",
            "citySpell":"tianshui"
        },
        {
            "airportCode":"JIC",
            "cityCName":"金昌",
            "cityEName":"jinchang",
            "cityFirstSpell":"jc",
            "citySpell":"jinchang"
        },
        {
            "airportCode":"RLK",
            "cityCName":"巴彦淖尔",
            "cityEName":"bayanzhuoer",
            "cityFirstSpell":"byne",
            "citySpell":"bayannaoer"
        },
        {
            "airportCode":"BPL",
            "cityCName":"博乐",
            "cityEName":"bole",
            "cityFirstSpell":"bl",
            "citySpell":"bole"
        },
        {
            "airportCode":"YIC",
            "cityCName":"宜春",
            "cityEName":"yichun",
            "cityFirstSpell":"yc",
            "citySpell":"yichun"
        },
        {
            "airportCode":"HPG",
            "cityCName":"湖北神农架",
            "cityEName":"shennongjia",
            "cityFirstSpell":"hbsnj",
            "citySpell":"hubeishennongjia"
        },
        {
            "airportCode":"BAR",
            "cityCName":"琼海",
            "cityEName":"Qionghai",
            "cityFirstSpell":"qh",
            "citySpell":"qionghai"
        },
        {
            "airportCode":"XTW",
            "cityCName":"邢台",
            "cityEName":"Xingtai airport",
            "cityFirstSpell":"xt",
            "citySpell":"xingtai"
        },
        {
            "airportCode":"WDS",
            "cityCName":"十堰",
            "cityEName":"SHIYAN",
            "cityFirstSpell":"sy",
            "citySpell":"shiyan"
        },
        {
            "airportCode":"HIA",
            "cityCName":"淮安",
            "cityEName":"Huaian",
            "cityFirstSpell":"ha",
            "citySpell":"huaian"
        },
        {
            "airportCode":"RIZ",
            "cityCName":"日照",
            "cityEName":"Rizhao airport",
            "cityFirstSpell":"rz",
            "citySpell":"rizhao"
        },
        {
            "airportCode":"BPE",
            "cityCName":"秦皇岛北戴河",
            "cityEName":"QINHUANGDAO BEIDAHE AIRPORT",
            "cityFirstSpell":"qhdbdh",
            "citySpell":"qinhuangdaobeidaihe"
        },
        {
            "airportCode":"RHT",
            "cityCName":"阿拉善右旗",
            "cityEName":"BADANJILIN",
            "cityFirstSpell":"alsyq",
            "citySpell":"alashanyouqi"
        },
        {
            "airportCode":"EJN",
            "cityCName":"额济纳旗",
            "cityEName":"ERJINA",
            "cityFirstSpell":"ejnq",
            "citySpell":"ejinaqi"
        },
        {
            "airportCode":"TLQ",
            "cityCName":"吐鲁番交河机场",
            "cityEName":"TULUFAN",
            "cityFirstSpell":"tlfjhjc",
            "citySpell":"tulufanjiaohejichang"
        },
        {
            "airportCode":"HMI",
            "cityCName":"哈密",
            "cityEName":"HAMI",
            "cityFirstSpell":"hmjc",
            "citySpell":"hamijichang"
        },
        {
            "airportCode":"YZY",
            "cityCName":"张掖",
            "cityEName":"ZHANGYE",
            "cityFirstSpell":"zy",
            "citySpell":"zhangye"
        },
        {
            "airportCode":"DCY",
            "cityCName":"稻城",
            "cityEName":"DAOCHENG",
            "cityFirstSpell":"dc",
            "citySpell":"daocheng"
        },
        {
            "airportCode":"CHG",
            "cityCName":"朝阳",
            "cityEName":"CHAOYANG",
            "cityFirstSpell":"cy",
            "citySpell":"chaoyang"
        },
        {
            "airportCode":"KJH",
            "cityCName":"黔东南",
            "cityEName":"KAILI",
            "cityFirstSpell":"qdn",
            "citySpell":"qiandongnan"
        },
        {
            "airportCode":"ACX",
            "cityCName":"黔西南",
            "cityEName":"XINGYI",
            "cityFirstSpell":"qxn",
            "citySpell":"qianxinan"
        },
        {
            "airportCode":"GYU",
            "cityCName":"宁夏固原",
            "cityEName":"guyuan",
            "cityFirstSpell":"nxgy",
            "citySpell":"ningxiaguyuan"
        },
        {
            "airportCode":"SQJ",
            "cityCName":"三明沙县机场",
            "cityEName":"SANMINGSHA",
            "cityFirstSpell":"smsxjc",
            "citySpell":"sanmingshaxianjichang"
        },
        {
            "airportCode":"LLV",
            "cityCName":"吕梁",
            "cityEName":"Lvliang",
            "cityFirstSpell":"ll",
            "citySpell":"lu:liang"
        },
        {
            "airportCode":"LLB",
            "cityCName":"南端荔波县",
            "cityEName":"Libo Airport",
            "cityFirstSpell":"ndlbx",
            "citySpell":"nanduanliboxian"
        },
        {
            "airportCode":"NLH",
            "cityCName":"泸沽湖",
            "cityEName":"Luguhuzhen",
            "cityFirstSpell":"lgh",
            "citySpell":"luguhu"
        },
        {
            "airportCode":"RKZ",
            "cityCName":"日喀则",
            "cityEName":"RIKAZE",
            "cityFirstSpell":"rkz",
            "citySpell":"rikaze"
        },
        {
            "airportCode":"YKH",
            "cityCName":"营口",
            "cityEName":"YINGKOU LANQI AIRPORT",
            "cityFirstSpell":"yk",
            "citySpell":"yingkou"
        },
        {
            "airportCode":"JUH",
            "cityCName":"安徽",
            "cityEName":"ANHUI",
            "cityFirstSpell":"ah",
            "citySpell":"anhui"
        },
        {
            "airportCode":"AXF",
            "cityCName":"阿拉善左旗",
            "cityEName":"BAYANHAOTE",
            "cityFirstSpell":"alszq",
            "citySpell":"alashanzuoqi"
        },
        {
            "airportCode":"AHJ",
            "cityCName":"红原",
            "cityEName":"Aba Hongyuan Airport",
            "cityFirstSpell":"hy",
            "citySpell":"hongyuan"
        },
        {
            "airportCode":"YTY",
            "cityCName":"扬州",
            "cityEName":"yangzhou",
            "cityFirstSpell":"yz",
            "citySpell":"yangzhou"
        },
        {
            "airportCode":"TCZ",
            "cityCName":"腾冲",
            "cityEName":"Tengchong",
            "cityFirstSpell":"tc",
            "citySpell":"tengchong"
        },
        {
            "airportCode":"OHE",
            "cityCName":"漠河",
            "cityEName":"MoHe",
            "cityFirstSpell":"mh",
            "citySpell":"mohe"
        },
        {
            "airportCode":"ZHY",
            "cityCName":"中卫",
            "cityEName":"Zhongwei",
            "cityFirstSpell":"zw",
            "citySpell":"zhongwei"
        },
        {
            "airportCode":"KJI",
            "cityCName":"喀纳斯",
            "cityEName":"KANASI",
            "cityFirstSpell":"kns",
            "citySpell":"kanasi"
        },
        {
            "airportCode":"NNY",
            "cityCName":"南阳",
            "cityEName":"NanYang",
            "cityFirstSpell":"ny",
            "citySpell":"nanyang"
        },
        {
            "airportCode":"DQA",
            "cityCName":"大庆",
            "cityEName":"Daqing",
            "cityFirstSpell":"dq",
            "citySpell":"daqing"
        },
        {
            "airportCode":"ERL",
            "cityCName":"二连浩特",
            "cityEName":"Erlianhaote",
            "cityFirstSpell":"elht",
            "citySpell":"erlianhaote"
        },
        {
            "airportCode":"KGT",
            "cityCName":"康定",
            "cityEName":"Kangding",
            "cityFirstSpell":"kd",
            "citySpell":"kangding"
        },
        {
            "airportCode":"JIQ",
            "cityCName":"黔江",
            "cityEName":"Qianjiang",
            "cityFirstSpell":"qj",
            "citySpell":"qianjiang"
        },
        {
            "airportCode":"JXA",
            "cityCName":"鸡西",
            "cityEName":"Jixi",
            "cityFirstSpell":"jx",
            "citySpell":"jixi"
        },
        {
            "airportCode":"LDS",
            "cityCName":"伊春",
            "cityEName":"Yichun",
            "cityFirstSpell":"yc",
            "citySpell":"yichun"
        },
        {
            "airportCode":"YUS",
            "cityCName":"玉树",
            "cityEName":"YuShu",
            "cityFirstSpell":"ys",
            "citySpell":"yushu"
        },
        {
            "airportCode":"WNH",
            "cityCName":"文山",
            "cityEName":"PUZHEHEI",
            "cityFirstSpell":"ws",
            "citySpell":"wenshan"
        },
        {
            "airportCode":"ZGC",
            "cityCName":"兰州",
            "cityEName":"Lanzhou",
            "cityFirstSpell":"lz",
            "citySpell":"zhongchuan"
        },
        {
            "airportCode":"YUA",
            "cityCName":"元谋",
            "cityEName":"YUANMOU",
            "cityFirstSpell":"ym",
            "citySpell":"yuanmou"
        },
        {
            "airportCode":"XIN",
            "cityCName":"兴宁",
            "cityEName":"XINGNING",
            "cityFirstSpell":"xn",
            "citySpell":"xingning"
        },
        {
            "airportCode":"THY",
            "cityCName":"中卫",
            "cityEName":"Zhongwei",
            "cityFirstSpell":"zw",
            "citySpell":"zhongwei"
        },
        {
            "airportCode":"SXJ",
            "cityCName":"膳善",
            "cityEName":"SHANSHAN",
            "cityFirstSpell":"ss",
            "citySpell":"shanshan"
        },
        {
            "airportCode":"SHF",
            "cityCName":"山海关",
            "cityEName":"SHANHAIGUAN",
            "cityFirstSpell":"shg",
            "citySpell":"shanhaiguan"
        },
        {
            "airportCode":"SIA",
            "cityCName":"西安",
            "cityEName":"XI AN",
            "cityFirstSpell":"xa",
            "citySpell":"xi'an"
        },
        {
            "airportCode":"NNN",
            "cityCName":"嫩江",
            "cityEName":"NENJIANG",
            "cityFirstSpell":"nj",
            "citySpell":"NENJIANG"
        },
        {
            "airportCode":"LUZ",
            "cityCName":"庐山",
            "cityEName":"LUSHAN",
            "cityFirstSpell":"ls",
            "citySpell":"LUSHAN"
        },
        {
            "airportCode":"LHK",
            "cityCName":"光化",
            "cityEName":"GUANGHUA",
            "cityFirstSpell":"gh",
            "citySpell":"guanghua"
        },
        {
            "airportCode":"LIA",
            "cityCName":"梁平",
            "cityEName":"LIANGPING",
            "cityFirstSpell":"lp",
            "citySpell":"liangping"
        },
        {
            "airportCode":"HSC",
            "cityCName":"韶关",
            "cityEName":"SHAOGUAN",
            "cityFirstSpell":"sg",
            "citySpell":"shaoguan"
        },
        {
            "airportCode":"DZU",
            "cityCName":"大足",
            "cityEName":"DAZU",
            "cityFirstSpell":"dz",
            "citySpell":"dazu"
        },
        {
            "airportCode":"AYN",
            "cityCName":"安阳",
            "cityEName":"ANYANG",
            "cityFirstSpell":"ay",
            "citySpell":"anyang"
        },
        {
            "airportCode":"LZJ",
            "cityCName":"丽江",
            "cityEName":"Lijiang",
            "cityFirstSpell":"lj",
            "citySpell":"lijiang"
        },
        {
            "airportCode":"FIG",
            "cityCName":"阜阳",
            "cityEName":"Fuyang",
            "cityFirstSpell":"fy",
            "citySpell":"fuyang"
        },
        {
            "airportCode":"WMT",
            "cityCName":"遵义茅台",
            "cityEName":"ZunyiMaotai",
            "cityFirstSpell":"zymt",
            "citySpell":"zunyimaotai"
        },
        {
            "airportCode":"YIE",
            "cityCName":"阿尔山",
            "cityEName":"Aershan",
            "cityFirstSpell":"aes",
            "citySpell":"Aershan"
        },
        {
            "airportCode":"NGQ",
            "cityCName":"阿里昆莎",
            "cityEName":"ALIKUNSHA",
            "cityFirstSpell":"alks",
            "citySpell":"ALIKUNSHA"
        },
        {
            "airportCode":"CWJ",
            "cityCName":"沧源",
            "cityEName":"CANGYUAN",
            "cityFirstSpell":"cy",
            "citySpell":"CANGYUAN"
        },
        {
            "airportCode":"CDE",
            "cityCName":"承德",
            "cityEName":"CHENGDE",
            "cityFirstSpell":"cd",
            "citySpell":"CHENGDE"
        },
        {
            "airportCode":"HXD",
            "cityCName":"德令哈",
            "cityEName":"DELINGHA",
            "cityFirstSpell":"dlh",
            "citySpell":"DELINGHA"
        },
        {
            "airportCode":"FYJ",
            "cityCName":"抚远",
            "cityEName":"FUYUAN",
            "cityFirstSpell":"fy",
            "citySpell":"FUYUAN"
        },
        {
            "airportCode":"GMQ",
            "cityCName":"果洛",
            "cityEName":"GUOLUO",
            "cityFirstSpell":"gl",
            "citySpell":"GUOLUO"
        },
        {
            "airportCode":"HCJ",
            "cityCName":"河池",
            "cityEName":"HECHI",
            "cityFirstSpell":"hc",
            "citySpell":"HECHI"
        },
        {
            "airportCode":"HTT",
            "cityCName":"花土沟",
            "cityEName":"HUATUGOU",
            "cityFirstSpell":"htg",
            "citySpell":"HUATUGOU"
        },
        {
            "airportCode":"HSQ",
            "cityCName":"黄石",
            "cityEName":"Huangshi",
            "cityFirstSpell":"hs",
            "citySpell":"Huangshi"
        },
        {
            "airportCode":"HUO",
            "cityCName":"霍林郭勒",
            "cityEName":"HUOLINGUOLE",
            "cityFirstSpell":"hlgl",
            "citySpell":"HUOLINGUOLE"
        },
        {
            "airportCode":"JGD",
            "cityCName":"加格达奇",
            "cityEName":"JiaGeDaQi",
            "cityFirstSpell":"jgdq",
            "citySpell":"JiaGeDaQi"
        },
        {
            "airportCode":"JSJ",
            "cityCName":"建三江",
            "cityEName":"JIANSANJIANG",
            "cityFirstSpell":"jsj",
            "citySpell":"JIANSANJIANG"
        },
        {
            "airportCode":"JIC",
            "cityCName":"金昌",
            "cityEName":"Jinchang",
            "cityFirstSpell":"jc",
            "citySpell":"Jinchang"
        },
        {
            "airportCode":"JMJ",
            "cityCName":"澜沧",
            "cityEName":"LANCANG",
            "cityFirstSpell":"lc",
            "citySpell":"LANCANG"
        },
        {
            "airportCode":"ZIY",
            "cityCName":"莲花山",
            "cityEName":"LIANHUASHAN",
            "cityFirstSpell":"lhs",
            "citySpell":"LIANHUASHAN"
        },
        {
            "airportCode":"LZN",
            "cityCName":"连江",
            "cityEName":"LIANJIANG",
            "cityFirstSpell":"lj",
            "citySpell":"LIANJIANG"
        },
        {
            "airportCode":"LPF",
            "cityCName":"六盘水",
            "cityEName":"LiuPanShui",
            "cityFirstSpell":"lps",
            "citySpell":"LiuPanShui"
        },
        {
            "airportCode":"XYI",
            "cityCName":"三沙",
            "cityEName":"SANSHA",
            "cityFirstSpell":"yx",
            "citySpell":"SANSHA"
        },
        {
            "airportCode":"QSZ",
            "cityCName":"莎车",
            "cityEName":"SHACHE",
            "cityFirstSpell":"sc",
            "citySpell":"SHACHE"
        },
        {
            "airportCode":"SQD",
            "cityCName":"上饶",
            "cityEName":"Shangrao",
            "cityFirstSpell":"sr",
            "citySpell":"Shangrao"
        },
        {
            "airportCode":"WGN",
            "cityCName":"邵阳",
            "cityEName":"Shaoyang",
            "cityFirstSpell":"sy",
            "citySpell":"Shaoyang"
        },
        {
            "airportCode":"YSQ",
            "cityCName":"松原",
            "cityEName":"Songyuan",
            "cityFirstSpell":"sy",
            "citySpell":"Songyuan"
        },
        {
            "airportCode":"UCB",
            "cityCName":"乌兰察布",
            "cityEName":"WULANCHABU",
            "cityFirstSpell":"wlbc",
            "citySpell":"WULANCHABU"
        },
        {
            "airportCode":"DTU",
            "cityCName":"五大连池",
            "cityEName":"WUDALIANCHI",
            "cityFirstSpell":"wdlc",
            "citySpell":"WUDALIANCHI"
        },
        {
            "airportCode":"GXH",
            "cityCName":"夏河",
            "cityEName":"XIAHE",
            "cityFirstSpell":"xh",
            "citySpell":"XIAHE"
        },
        {
            "airportCode":"NZL",
            "cityCName":"扎兰屯",
            "cityEName":"ZHAKANTUN",
            "cityFirstSpell":"zlt",
            "citySpell":"ZHAKANTUN"
        },
        {
            "airportCode":"ZQZ",
            "cityCName":"张家口",
            "cityEName":"ZHANGJIAKOU",
            "cityFirstSpell":"ny",
            "citySpell":"ZHANGJIAKOU"
        },
        {
            "airportCode":"LFQ",
            "cityCName":"临汾市",
            "cityEName":"Linfeng",
            "cityFirstSpell":"lf",
            "citySpell":"linfen"
        }
    ],
    "addressAirportHot":[
      {
          "airportCode":"PEK",
          "cityCName":"北京首都",
          "cityEName":"beijing",
          "cityFirstSpell":"bj",
          "citySpell":"beijing"
      },
        {
            "airportCode":"PKX",
            "cityCName":"北京大兴国际",
            "cityEName":"Beijingnanyuan",
            "cityFirstSpell":"bj",
            "citySpell":"beijing"
        },
		{
		    "airportCode":"PVG",
		    "cityCName":"上海浦东",
		    "cityEName":"Shanghai",
		    "cityFirstSpell":"sh",
		    "citySpell":"shanghai"
		},
		{
		    "airportCode":"SHA",
		    "cityCName":"上海虹桥",
		    "cityEName":"Shanghai",
		    "cityFirstSpell":"sh",
		    "citySpell":"shanghai"
		},
		{
		    "airportCode":"CAN",
		    "cityCName":"广州",
		    "cityEName":"Guangzhou",
		    "cityFirstSpell":"gz",
		    "citySpell":"guangzhou"
		},
		{
		    "airportCode":"SZX",
		    "cityCName":"深圳",
		    "cityEName":"Shenzhen",
		    "cityFirstSpell":"sz",
		    "citySpell":"shenzhen"
		},
        {
            "airportCode":"WUH",
            "cityCName":"武汉",
            "cityEName":"Wuhan",
            "cityFirstSpell":"wh",
            "citySpell":"wuhan"
        },
        {
            "airportCode":"CSX",
            "cityCName":"长沙",
            "cityEName":"Changsha",
            "cityFirstSpell":"cs",
            "citySpell":"Changsha"
        },
        {
            "airportCode":"CGO",
            "cityCName":"郑州",
            "cityEName":"Zhengzhou",
            "cityFirstSpell":"zz",
            "citySpell":"zhengzhou"
        },
        {
            "airportCode":"NKG",
            "cityCName":"南京",
            "cityEName":"Nanjing",
            "cityFirstSpell":"nj",
            "citySpell":"nanjing"
        },
        {
            "airportCode":"DLC",
            "cityCName":"大连",
            "cityEName":"Dalian",
            "cityFirstSpell":"dl",
            "citySpell":"dalian"
        },
        {
            "airportCode":"TNA",
            "cityCName":"济南",
            "cityEName":"Jinan",
            "cityFirstSpell":"jn",
            "citySpell":"jinan"
        },
       
        {
            "airportCode":"TAO",
            "cityCName":"青岛",
            "cityEName":"Qingdao",
            "cityFirstSpell":"qd",
            "citySpell":"qingdao"
        },
       
        {
            "airportCode":"CTU",
            "cityCName":"成都",
            "cityEName":"Chengdu",
            "cityFirstSpell":"cd",
            "citySpell":"chengdou"
        },
        {
            "airportCode":"TSN",
            "cityCName":"天津",
            "cityEName":"Tianjin",
            "cityFirstSpell":"tj",
            "citySpell":"tianjin"
        },
       
        {
            "airportCode":"SYX",
            "cityCName":"三亚",
            "cityEName":"Sanya",
            "cityFirstSpell":"sy",
            "citySpell":"sanya"
        },
       
        {
            "airportCode":"KMG",
            "cityCName":"昆明",
            "cityEName":"Kunming",
            "cityFirstSpell":"km",
            "citySpell":"kunming"
        },
        {
            "airportCode":"HGH",
            "cityCName":"杭州",
            "cityEName":"Hangzhou",
            "cityFirstSpell":"hz",
            "citySpell":"hangzhou"
        },
        {
            "airportCode":"CKG",
            "cityCName":"重庆",
            "cityEName":"Chongqing",
            "cityFirstSpell":"zq",
            "citySpell":"zhongqing"
        },
        {
            "airportCode":"FOC",
            "cityCName":"福州",
            "cityEName":"Fuzhou",
            "cityFirstSpell":"fz",
            "citySpell":"fuzhou"
        },
        {
            "airportCode":"XMN",
            "cityCName":"厦门",
            "cityEName":"Xiamen",
            "cityFirstSpell":"sm",
            "citySpell":"shamen"
        },
		{
		    "airportCode":"HAK",
		    "cityCName":"海口",
		    "cityEName":"Haikou",
		    "cityFirstSpell":"hk",
		    "citySpell":"haikou"
		},{
            "airportCode":"HUZ",
            "cityCName":"惠州",
            "cityEName":"Huizhou",
            "cityFirstSpell":"hz",
            "citySpell":"huizhou"
        }
    ]
}